<template>
	<div>
		admin

		<button @click="getcitydatas">indexdata</button>
            <br>
            <br>
            <br>
            <br>
        <button @click="getFindCarousel">getFindCarousel</button>
                <br>
                            <br>
            <br>
        <button @click='savedetails'>savwdetails{{msg}}</button>


	</div>


</template>


<script>
import axios from 'axios'
    import {mapState,mapGetters,mapMutations} from 'vuex'

export default{
   computed:{
           
            ...mapState({
                msg:(state)=>state.user.msg
                

            })
        }
    ,

	methods:{
		
		getcitydatas(){
			var pro ={
        "group_section":{
            "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRnYxJTJGd2ViJTJGd2Vla19jaG9pY2UuanNvbiUyMiUyQyUyMl9xdWVyeSUyMiUzQSUyMnBhZ2UlM0QwJTI2Y2l0eV9pZCUzRDIzNSUyMiUyQyUyMnRpdGxlJTIyJTNBJTIyJUU2JUFGJThGJUU1JTkxJUE4JUU3JUIyJUJFJUU5JTgwJTg5JUU5JUE0JTkwJUU5JUE1JUFFJTIyJTdE",
            "desc":"8月7日更新",
            "title":"每周精选餐饮"
        },
        "tabs":[
            {
                "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRnYxJTJGd2ViJTJGd2Vla19jaG9pY2UuanNvbiUyMiUyQyUyMl9xdWVyeSUyMiUzQSUyMnBhZ2UlM0QwJTI2Y2l0eV9pZCUzRDIzNSUyMiUyQyUyMnByaWNlJTIyJTNBJTIyMTM5JTIyJTJDJTIyaWQlMjIlM0ElMjI1MDgyOTgwJTIyJTJDJTIydGl0bGUlMjIlM0ElMjIlRTQlQjglOUMlRTYlOTYlQjklRTUlQjklQkYlRTUlOUMlQkElRTUlODElODclRTYlOTclQTUlRTklODUlOTIlRTUlQkElOTclRTglOUMlODAlRTUlOTIlOTYlRTUlOTUlQTElRTglOUElOUQlRTglOTklQkUlRTUlOTUlQTQlRTklODUlOTIlRTUlQTQlOUMlRTUlOEQlOTUlRTQlQkElQkElRTglODclQUElRTUlOEElQTklRTYlOTklOUElRTklQTQlOTAlMjIlMkMlMjJ0eXBlJTIyJTNBJTIycHJvZHVjdCUyMiUyQyUyMmVuam95VXJsJTIyJTNBJTIyZW5qb3lhcHAlM0ElMkYlMkZwcm9kdWN0JTJGZGV0YWlsJTNGaWQlM0QxMDM5MzQ0JTI2c3ViLXByb2R1Y3QtaWQlM0Q1MDgyOTgwJTIyJTdE",
                "desc":"尽享鲜虾生蚝盛宴",
                "enjoy_url":"enjoyapp://product/detail?id=1039344&sub-product-id=5082980",
                "entity_name":"位",
                "ext":{
                    "product_type":0
                },
                "group":false,
                "id":"5082980",
                "original_price":"¥258",
                "price":"139",
                "tag":"春熙路",
                "title":"东方广场假日酒店蜀咖啡蚝虾啤酒夜单人自助晚餐",
                "type":"product",
                "url":"https://image.ricebook.com/business/20693050723276",
                "url_type":"image"
            },
            {
                "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRnYxJTJGd2ViJTJGd2Vla19jaG9pY2UuanNvbiUyMiUyQyUyMl9xdWVyeSUyMiUzQSUyMnBhZ2UlM0QwJTI2Y2l0eV9pZCUzRDIzNSUyMiUyQyUyMnByaWNlJTIyJTNBJTIyMTI4JTIyJTJDJTIyaWQlMjIlM0ElMjI1MDg5NjA1JTIyJTJDJTIydGl0bGUlMjIlM0ElMjJWSU5PVEVLQSVFNiVCMyU5NSVFNSVCQyU4RiVFNyU4MyVBNCVFOCU4MiU4OSVFNSU4RCU5NSVFNyU4MiVCOSVFNSVCQyU4RiVFOCU4NyVBQSVFNSU4QSVBOSUyMiUyQyUyMnR5cGUlMjIlM0ElMjJwcm9kdWN0JTIyJTJDJTIyZW5qb3lVcmwlMjIlM0ElMjJlbmpveWFwcCUzQSUyRiUyRnByb2R1Y3QlMkZkZXRhaWwlM0ZpZCUzRDEwNDI0MDQlMjZzdWItcHJvZHVjdC1pZCUzRDUwODk2MDUlMjIlN0Q=",
                "desc":"法式烤肉与美酒畅享",
                "enjoy_url":"enjoyapp://product/detail?id=1042404&sub-product-id=5089605",
                "entity_name":"位",
                "ext":{
                    "product_type":0
                },
                "group":false,
                "id":"5089605",
                "original_price":"¥158",
                "price":"128",
                "tag":"春熙路",
                "title":"VINOTEKA法式烤肉单点式自助",
                "type":"product",
                "url":"https://image.ricebook.com/business/21164538023864",
                "url_type":"image"
            },
            {
                "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRnYxJTJGd2ViJTJGd2Vla19jaG9pY2UuanNvbiUyMiUyQyUyMl9xdWVyeSUyMiUzQSUyMnBhZ2UlM0QwJTI2Y2l0eV9pZCUzRDIzNSUyMiUyQyUyMnByaWNlJTIyJTNBJTIyMjI4JTIyJTJDJTIyaWQlMjIlM0ElMjI1MDI5NzA0JTIyJTJDJTIydGl0bGUlMjIlM0ElMjIlRTYlOUMlQjQlRTclOTQlQjAlRTYlQjMlQjAlRTUlQkMlOEYlRTYlQjUlQjclRTklQjIlOUMlRTclODElQUIlRTklOTQlODUlRUYlQkMlODglRTYlQjMlOUIlRTYlODIlQTYlRTUlOUIlQkQlRTklOTklODUlRTUlQkElOTclRUYlQkMlODklRTUlOEYlOEMlRTQlQkElQkElRTklQTQlOTAlMjIlMkMlMjJ0eXBlJTIyJTNBJTIycHJvZHVjdCUyMiUyQyUyMmVuam95VXJsJTIyJTNBJTIyZW5qb3lhcHAlM0ElMkYlMkZwcm9kdWN0JTJGZGV0YWlsJTNGaWQlM0QxMDE1NTg1JTI2c3ViLXByb2R1Y3QtaWQlM0Q1MDI5NzA0JTIyJTdE",
                "desc":"汤底奶香浓郁 海鲜新鲜到店",
                "enjoy_url":"enjoyapp://product/detail?id=1015585&sub-product-id=5029704",
                "entity_name":"2位",
                "ext":{
                    "product_type":0
                },
                "group":false,
                "id":"5029704",
                "original_price":"¥268",
                "price":"228",
                "tag":"科华北路",
                "title":"朴田泰式海鲜火锅（泛悦国际店）双人餐",
                "type":"product",
                "url":"https://image.ricebook.com/business/17723378223902",
                "url_type":"image"
            },
            {
                "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRnYxJTJGd2ViJTJGd2Vla19jaG9pY2UuanNvbiUyMiUyQyUyMl9xdWVyeSUyMiUzQSUyMnBhZ2UlM0QwJTI2Y2l0eV9pZCUzRDIzNSUyMiUyQyUyMnByaWNlJTIyJTNBJTIyMzE1JTIyJTJDJTIyaWQlMjIlM0ElMjI1MDg4NzQ2JTIyJTJDJTIydGl0bGUlMjIlM0ElMjIlRTUlQjAlOEYlRTYlQjUlQjclRTUlQTAlODIlRTclQjIlQkUlRTglODclQjQlRTUlOEYlOEMlRTQlQkElQkElRTklQTQlOTAlMjIlMkMlMjJ0eXBlJTIyJTNBJTIycHJvZHVjdCUyMiUyQyUyMmVuam95VXJsJTIyJTNBJTIyZW5qb3lhcHAlM0ElMkYlMkZwcm9kdWN0JTJGZGV0YWlsJTNGaWQlM0QxMDM5NzkzJTI2c3ViLXByb2R1Y3QtaWQlM0Q1MDg4NzQ2JTIyJTdE",
                "desc":"色泽金红味美可口的金牌烧鹅",
                "enjoy_url":"enjoyapp://product/detail?id=1039793&sub-product-id=5088746",
                "entity_name":"2位",
                "ext":{
                    "product_type":0
                },
                "group":false,
                "id":"5088746",
                "original_price":"¥332",
                "price":"315",
                "tag":"大慈寺",
                "title":"小海堂精致双人餐",
                "type":"product",
                "url":"https://image.ricebook.com/business/20747225123096",
                "url_type":"image"
            },
            {
                "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRnYxJTJGd2ViJTJGd2Vla19jaG9pY2UuanNvbiUyMiUyQyUyMl9xdWVyeSUyMiUzQSUyMnBhZ2UlM0QwJTI2Y2l0eV9pZCUzRDIzNSUyMiUyQyUyMnByaWNlJTIyJTNBJTIyOTglMjIlMkMlMjJpZCUyMiUzQSUyMjUwODkxOTYlMjIlMkMlMjJ0aXRsZSUyMiUzQSUyMiVFNiU5RSU4MSVFOSVBMyU5RiVFRiVCQyU4OCVFOCVCRiU5QyVFNiVCNCU4QiVFNSVBNCVBQSVFNSU4RiVBNCVFOSU4NyU4QyVFNSVCQSU5NyVFRiVCQyU4OSVFNSVBNCU4RiVFNiU5NyVBNSVFNSU4NSVBOCVFNiU5NiVCMCVFNSU4RiU4QyVFNCVCQSVCQSVFNCVCOCU4QiVFNSU4RCU4OCVFOCU4QyVCNiUyMiUyQyUyMnR5cGUlMjIlM0ElMjJwcm9kdWN0JTIyJTJDJTIyZW5qb3lVcmwlMjIlM0ElMjJlbmpveWFwcCUzQSUyRiUyRnByb2R1Y3QlMkZkZXRhaWwlM0ZpZCUzRDEwNDIyMzElMjZzdWItcHJvZHVjdC1pZCUzRDUwODkxOTYlMjIlN0Q=",
                "desc":"远洋太古里即摘即食的乐活餐厅",
                "enjoy_url":"enjoyapp://product/detail?id=1042231&sub-product-id=5089196",
                "entity_name":"2位",
                "ext":{
                    "product_type":0
                },
                "group":false,
                "id":"5089196",
                "original_price":"¥148",
                "price":"98",
                "tag":"大慈寺",
                "title":"极食（远洋太古里店）夏日全新双人下午茶",
                "type":"product",
                "url":"https://image.ricebook.com/business/21118428723850",
                "url_type":"image"
            },
            {
                "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRnYxJTJGd2ViJTJGd2Vla19jaG9pY2UuanNvbiUyMiUyQyUyMl9xdWVyeSUyMiUzQSUyMnBhZ2UlM0QwJTI2Y2l0eV9pZCUzRDIzNSUyMiUyQyUyMnByaWNlJTIyJTNBJTIyNDklMjIlMkMlMjJpZCUyMiUzQSUyMjUwOTAxMjclMjIlMkMlMjJ0aXRsZSUyMiUzQSUyMiVFNSVCRSVCNyVFNSVCQSVCNyVFNiU4MSU5MiVFNyU4MiVCOSVFNSVCRiU4MyVFOSU5MyVCQSVFNSU4RCU5NSVFNCVCQSVCQSVFOSVBNCU5MCUyMiUyQyUyMnR5cGUlMjIlM0ElMjJwcm9kdWN0JTIyJTJDJTIyZW5qb3lVcmwlMjIlM0ElMjJlbmpveWFwcCUzQSUyRiUyRnByb2R1Y3QlMkZkZXRhaWwlM0ZpZCUzRDEwNDI2MjAlMjZzdWItcHJvZHVjdC1pZCUzRDUwOTAxMjclMjIlN0Q=",
                "desc":"地道粤式好味",
                "enjoy_url":"enjoyapp://product/detail?id=1042620&sub-product-id=5090127",
                "entity_name":"1位",
                "ext":{
                    "product_type":0
                },
                "group":false,
                "id":"5090127",
                "original_price":"¥76",
                "price":"49",
                "tag":"春熙路",
                "title":"德康恒点心铺单人餐",
                "type":"product",
                "url":"https://image.ricebook.com/business/21205913823172",
                "url_type":"image"
            },
            {
                "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRnYxJTJGd2ViJTJGd2Vla19jaG9pY2UuanNvbiUyMiUyQyUyMl9xdWVyeSUyMiUzQSUyMnBhZ2UlM0QwJTI2Y2l0eV9pZCUzRDIzNSUyMiUyQyUyMnByaWNlJTIyJTNBJTIyMjQ4JTIyJTJDJTIyaWQlMjIlM0ElMjI1MDg0Njg4JTIyJTJDJTIydGl0bGUlMjIlM0ElMjIlRTglOEIlOEYlRTUlOUQlQTYlRTQlQjglQUQlRTQlQjglOUMlRTYlOTYlOTklRTclOTAlODYlRUYlQkMlODglRTUlQTQlQUElRTUlOEYlQTQlRTklODclOEMlRTYlOTclOTclRTglODglQjAlRTUlQkElOTclRUYlQkMlODklRTUlODUlQTglRTYlOTYlQjAlRTUlOEYlOEMlRTQlQkElQkElRTklQTQlOTAlMjIlMkMlMjJ0eXBlJTIyJTNBJTIycHJvZHVjdCUyMiUyQyUyMmVuam95VXJsJTIyJTNBJTIyZW5qb3lhcHAlM0ElMkYlMkZwcm9kdWN0JTJGZGV0YWlsJTNGaWQlM0QxMDQwMjcyJTI2c3ViLXByb2R1Y3QtaWQlM0Q1MDg0Njg4JTIyJTdE",
                "desc":"土耳其黎巴嫩摩洛哥等多款中东美食一餐齐享",
                "enjoy_url":"enjoyapp://product/detail?id=1040272&sub-product-id=5084688",
                "entity_name":"2位",
                "ext":{
                    "product_type":0
                },
                "group":false,
                "id":"5084688",
                "original_price":"¥325",
                "price":"248",
                "tag":"大慈寺",
                "title":"苏坦中东料理（太古里旗舰店）全新双人餐",
                "type":"product",
                "url":"https://image.ricebook.com/business/20807934823504",
                "url_type":"image"
            },
            {
                "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRnYxJTJGd2ViJTJGd2Vla19jaG9pY2UuanNvbiUyMiUyQyUyMl9xdWVyeSUyMiUzQSUyMnBhZ2UlM0QwJTI2Y2l0eV9pZCUzRDIzNSUyMiUyQyUyMnByaWNlJTIyJTNBJTIyNzklMjIlMkMlMjJpZCUyMiUzQSUyMjUwOTAwMDYlMjIlMkMlMjJ0aXRsZSUyMiUzQSUyMkVOSk9ZJTIwJUMzJTk3JTIwJUU1JUE0JUE3JUU1JUJFJUI3JUU1JUE0JThGJUU2JTk3JUE1JUU3JUE2JThGJUU4JUEyJThCJTIyJTJDJTIydHlwZSUyMiUzQSUyMnByb2R1Y3QlMjIlMkMlMjJlbmpveVVybCUyMiUzQSUyMmVuam95YXBwJTNBJTJGJTJGcHJvZHVjdCUyRmRldGFpbCUzRmlkJTNEMTA0MjQ1NyUyNnN1Yi1wcm9kdWN0LWlkJTNENTA5MDAwNiUyMiU3RA==",
                "desc":"超值福利 限量发售",
                "enjoy_url":"enjoyapp://product/detail?id=1042457&sub-product-id=5090006",
                "entity_name":"份",
                "ext":{
                    "product_type":1
                },
                "group":false,
                "id":"5090006",
                "price":"79",
                "tag":"春熙路",
                "title":"ENJOY × 大德夏日福袋",
                "type":"product",
                "url":"https://image.ricebook.com/business/21172700623367",
                "url_type":"image"
            },
            {
                "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRnYxJTJGd2ViJTJGd2Vla19jaG9pY2UuanNvbiUyMiUyQyUyMl9xdWVyeSUyMiUzQSUyMnBhZ2UlM0QwJTI2Y2l0eV9pZCUzRDIzNSUyMiUyQyUyMnByaWNlJTIyJTNBJTIyMTQ4JTIyJTJDJTIyaWQlMjIlM0ElMjI1MDM1MTYzJTIyJTJDJTIydGl0bGUlMjIlM0ElMjIlRTUlQjglOEMlRTUlQjAlOTQlRTklQTElQkYlQzIlQjclRTUlQkUlQTElRTclOEUlQkElRTQlQjglQUQlRTklQTQlOTAlRTUlOEUlODUlRTQlQjglQkIlRTUlOEUlQTglRTclODIlQjklRTUlQkYlODMlRTglOEElODIlRTUlOEQlODglRTUlQjglODIlRTclODIlQjklRTUlQkYlODMlRTglODclQUElRTUlOEElQTklMjIlMkMlMjJ0eXBlJTIyJTNBJTIycHJvZHVjdCUyMiUyQyUyMmVuam95VXJsJTIyJTNBJTIyZW5qb3lhcHAlM0ElMkYlMkZwcm9kdWN0JTJGZGV0YWlsJTNGaWQlM0QxMDA5Mzg4JTI2c3ViLXByb2R1Y3QtaWQlM0Q1MDM1MTYzJTIyJTdE",
                "desc":"佛山星级大厨礼备十余新款点心任选 ",
                "enjoy_url":"enjoyapp://product/detail?id=1009388&sub-product-id=5035163",
                "entity_name":"位",
                "ext":{
                    "product_type":0
                },
                "group":false,
                "id":"5035163",
                "original_price":"¥160",
                "price":"148",
                "tag":"高新区",
                "title":"希尔顿·御玺中餐厅主厨点心节午市点心自助",
                "type":"product",
                "url":"https://image.ricebook.com/business/21178875023735",
                "url_type":"image"
            },
            {
                "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRnYxJTJGd2ViJTJGd2Vla19jaG9pY2UuanNvbiUyMiUyQyUyMl9xdWVyeSUyMiUzQSUyMnBhZ2UlM0QwJTI2Y2l0eV9pZCUzRDIzNSUyMiUyQyUyMnByaWNlJTIyJTNBJTIyNDQ4JTIyJTJDJTIyaWQlMjIlM0ElMjI1MDI5NzA2JTIyJTJDJTIydGl0bGUlMjIlM0ElMjIlRTYlOUMlQjQlRTclOTQlQjAlRTYlQjMlQjAlRTUlQkMlOEYlRTYlQjUlQjclRTklQjIlOUMlRTclODElQUIlRTklOTQlODUlRUYlQkMlODglRTYlQjMlOUIlRTYlODIlQTYlRTUlOUIlQkQlRTklOTklODUlRTUlQkElOTclRUYlQkMlODklRTUlOUIlOUIlRTQlQkElQkElRTklQTQlOTAlMjIlMkMlMjJ0eXBlJTIyJTNBJTIycHJvZHVjdCUyMiUyQyUyMmVuam95VXJsJTIyJTNBJTIyZW5qb3lhcHAlM0ElMkYlMkZwcm9kdWN0JTJGZGV0YWlsJTNGaWQlM0QxMDE1NTg0JTI2c3ViLXByb2R1Y3QtaWQlM0Q1MDI5NzA2JTIyJTdE",
                "desc":"金丝设计的独栋复式洋楼",
                "enjoy_url":"enjoyapp://product/detail?id=1015584&sub-product-id=5029706",
                "entity_name":"4位",
                "ext":{
                    "product_type":0
                },
                "group":false,
                "id":"5029706",
                "original_price":"¥524",
                "price":"448",
                "tag":"科华北路",
                "title":"朴田泰式海鲜火锅（泛悦国际店）四人餐",
                "type":"product",
                "url":"https://image.ricebook.com/business/17764972413612",
                "url_type":"image"
            }
        ]
    }

			axios.post('/api/getcitydata',pro)
						.then(function(res){
							console.log(res)
						})


			},
            getFindCarousel(){

                var pro = {
                    img:'https://image.ricebook.com/business/23175261623972?imageView2/2/w/670' ,
                    text1:"超级星期五",
                    text2:'满450减45元 满180减15元！春天里，约会你',
                    text3:'一览蓉城春景的星级酒店、浪漫满分的精致西餐厅......白色情人节特辑'
                }
                axios.post('/api/getfindcarousel',pro)
                        .then(function(res){
                            console.log(res)
                        })
            },
            savedetails(){
                var pro = {
    "modules":[
        {
            "compatibility_policy":{
                "alert_message":"当前应用版本太低",
                "policy":"alert"
            },
            "data":{
                "restaurants":[
                    {
                        "area_id":2367,
                        "area_name":"春熙路",
                        "city_id":0,
                        "enjoy_url":"enjoyapp://restaurant/profile?id=428241",
                        "latitude":30.64797592163086,
                        "license":{
                            "enjoy_url":"https://topic.ricebook.com/topicpage/product_licence.html?restaurant_id=428241",
                            "icon":"https://image.ricebook.com/business/18915887513738",
                            "text":"营业许可资质"
                        },
                        "longitude":104.0887451171875,
                        "price_number":0,
                        "restaurant_address":"锦江区东大街芷泉段231号东方广场假日酒店一楼大堂",
                        "restaurant_id":428241,
                        "restaurant_image":[
                            {
                                "img_url":"https://image.ricebook.com/business/16256675213179",
                                "special_show":false
                            },
                            {
                                "img_url":"https://image.ricebook.com/business/16256675213330",
                                "special_show":false
                            }
                        ],
                        "restaurant_name":"东方广场假日酒店·蜀咖啡",
                        "restaurant_phone_numbers":[
                            "028-61303751"
                        ],
                        "state":0
                    }
                ]
            },
            "id":5,
            "index":1
        },
        {
            "compatibility_policy":{
                "alert_message":"当前应用版本太低",
                "policy":"ignore"
            },
            "data":{
                "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRmluZm8lMkZwcm9kdWN0X2RldGFpbC5qc29uJTIyJTJDJTIyX3F1ZXJ5JTIyJTNBJTIyc3ViX3Byb2R1Y3RfaWQlM0Q1MDgyOTgwJTI2cHJvZHVjdF9pZCUzRDEwMzkzNDQlMjIlMkMlMjJzdWJQcm9kdWN0SWQlMjIlM0E1MDgyOTgwJTJDJTIyc291cmNlJTIyJTNBJTIycHJvZHVjdCUyMiUyQyUyMnRleHQlMjIlM0ElMjIlRTQlQjglQkElRTQlQkElODYlRTclODUlQTclRTklQTElQkUlRTglODAlODElRTQlQjglQUQlRTklOUQlOTIlRUYlQkMlOEMlRTklODAlODklRTYlOUQlQTUlRTklODAlODklRTUlOEUlQkIlRTklODAlODklRTQlQkElODYlRTglQkYlOTklRTUlQUUlQjYlRTMlODAlODIlRTYlOUUlOUMlRTclODQlQjYlRTUlQTQlQTclRTUlQUUlQjYlRTklODMlQkQlRTYlOUMlODklRTUlOTYlOUMlRTYlQUMlQTIlRTclOUElODQlRTglOEYlOUMlRTUlOTMlODElRTMlODAlODIlRTglOEYlOUMlRTUlOTMlODElRTclQUUlOTclRTYlQUYlOTQlRTglQkUlODMlRTQlQjglQjAlRTUlQUYlOEMlRUYlQkMlOEMlRTQlQjklOUYlRTglOUIlQUUlRTYlOTYlQjAlRTklQjIlOUMlRUYlQkMlODglRTclODElQUIlRTklOTQlODUlRTUlOEMlQkElRTglOTQlQUMlRTglOEYlOUMlRTUlOTMlODElRTglQjQlQTglRTclOTUlQTUlRTUlQjclQUUlRUYlQkMlOEMlRTUlODUlQjYlRTUlQUUlODMlRTklODMlQkQlRTQlQjglOEQlRTklOTQlOTklRUYlQkMlODklRTMlODAlODIlRTclOTQlOUMlRTUlOTMlODElRTMlODAlODElRTUlQjAlOEYlRTklQkUlOTklRTglOTklQkUlRTUlOTIlOEMlRTYlQjUlQjclRTklQjIlOUMlRTklODMlQkQlRTglOUIlQUUlRTUlQTUlQkQlRTMlODAlODIlRTUlQUYlQjklRTUlOUIlOUIlRTUlQjclOUQlRTglODMlODMlRTQlQjklOUYlRTclOUIlQjglRTUlQkQlOTMlRTclODUlQTclRTklQTElQkUlRTMlODAlODIlRTklQjglQTElRTUlQjAlQkUlRTklODUlOTIlRTklQTIlOUMlRTglODklQjIlRTclQkUlOEUlRTQlQkQlODYlRTUlOTElQjMlRTklODElOTMlRTUlQTQlQUElRTYlQjclQTElRTMlODAlODIlRTQlQjglOEQlRTglQjYlQjMlRTYlOTglQUY4JUU3JTgyJUI5JUU4JUJGJTg3JUU1JUJFJTg4JUU1JUE0JTlBJUU4JThGJTlDJUU1JTkzJTgxJUU1JUIwJUIxJUU2JUIyJUExJUU2JTlDJTg5JUU0JUJBJTg2JUUyJTgwJUE2JUU4JUFGJTlEJUU4JUFGJUI0JUU4JTg3JUFBJUU1JThBJUE5JUU5JUE0JTkwJUU4JUJGJTk5JUU2JUEwJUI3JUU0JUI4JThEJUU1JUE1JUJEJUU1JTkwJUE3JUUyJTgwJUE2JUU2JTgwJUJCJUU0JUJEJTkzJUU1JTgwJUJDJUU1JUJFJTk3JUU1JTg2JThEJUU1JThFJUJCJUU3JTlBJTg0JUU5JUE0JTkwJUU1JThFJTg1JTIyJTJDJTIyaWQlMjIlM0ExNTAyMDYwMTg5NDAwMDAxJTJDJTIycmVzdGF1cmFudElkJTIyJTNBMCUyQyUyMmVuam95VXJsJTIyJTNBJTIyZW5qb3lhcHAlM0ElMkYlMkZwcm9kdWN0JTJGZmVlZGJhY2slMkZsaXN0JTNGcHJvZHVjdF9pZCUzRDEwMzkzNDQlMjIlN0Q=",
                "avatar":"https://image.ricebook.com/business/22268465023065",
                "create_time":1502060189000,
                "enjoy_url":"enjoyapp://product/feedback/list?product_id=1039344",
                "id":1502060189400001,
                "images":[
                    "https://image.ricebook.com/feedback/1502060187340002",
                    "https://image.ricebook.com/feedback/1502060189340002"
                ],
                "merchant_id":2991,
                "nick_name":"ENJOY_623zXLVd",
                "order_id":"1501760205320001",
                "restaurant_id":0,
                "scores":[
                    {
                        "id":3,
                        "name":"菜品质量",
                        "score":5
                    },
                    {
                        "id":4,
                        "name":"就餐环境",
                        "score":5
                    },
                    {
                        "id":5,
                        "name":"餐厅服务",
                        "score":5
                    }
                ],
                "source":"product",
                "sub_product_id":5082980,
                "tags":[
                    {
                        "id":31,
                        "name":"干净卫生"
                    },
                    {
                        "id":18,
                        "name":"摆盘精美"
                    },
                    {
                        "id":17,
                        "name":"食材新鲜"
                    },
                    {
                        "id":16,
                        "name":"好吃"
                    },
                    {
                        "id":27,
                        "name":"服务周到"
                    }
                ],
                "text":"为了照顾老中青，选来选去选了这家。果然大家都有喜欢的菜品。菜品算比较丰富，也蛮新鲜（火锅区蔬菜品质略差，其它都不错）。甜品、小龙虾和海鲜都蛮好。对四川胃也相当照顾。鸡尾酒颜色美但味道太淡。不足是8点过很多菜品就没有了…话说自助餐这样不好吧…总体值得再去的餐厅",
                "update_time":1510418225000,
                "user_id":21246567924239
            },
            "id":16,
            "index":2
        },
        {
            "compatibility_policy":{
                "alert_message":"当前应用版本太低",
                "policy":"alert"
            },
            "data":{
                "contents":[
                    {
                        "sub_title":"温馨提示",
                        "text":[
                            "此菜单仅提供菜系作为参考，具体菜品请以酒店当日供应为准"
                        ]
                    },
                    {
                        "sub_title":"刺身",
                        "text":[
                            "川式三文鱼",
                            "泰式三文鱼",
                            "三文鱼刺身",
                            "鲷鱼",
                            "大八爪鱼",
                            "希鲮鱼",
                            "醋鲭鱼"
                        ]
                    },
                    {
                        "sub_title":"海鲜冰槽",
                        "text":[
                            "蓝口贝",
                            "扇贝",
                            "虾",
                            "青口",
                            "翡翠螺",
                            "鳕蟹腿"
                        ]
                    },
                    {
                        "sub_title":"寿司",
                        "text":[
                            "寿司正卷",
                            "寿司花卷",
                            "寿司手握",
                            "加州卷"
                        ]
                    },
                    {
                        "sub_title":"现场制作档口",
                        "text":[
                            "现开刺身生蚝",
                            "蒜茸烤生蚝",
                            "芝士焗生蚝"
                        ]
                    },
                    {
                        "sub_title":"现场炒小海鲜",
                        "text":[
                            "【海鲜】",
                            "文蛤",
                            "花甲",
                            "蛤蜊",
                            "雪蛤",
                            "圣子",
                            "海瓜子",
                            "虾",
                            "螺肉",
                            "鱿鱼须 ",
                            "【配素菜】",
                            "藕条",
                            "青笋条",
                            "土豆条"
                        ]
                    },
                    {
                        "sub_title":"川式特色海鲜",
                        "text":[
                            "爆炒土龙虾（蒜蓉，香辣）（中）",
                            "香辣蓝口贝（中）",
                            "姜葱大虾（中）",
                            "避风塘炒虾",
                            "特色中式凉卤档",
                            "卤龙虾（中），油焖虾（中） 卤菜档 兔头",
                            "鸭头",
                            "鸡尖翅",
                            "郡肝",
                            "君把",
                            "鸡心",
                            "冷吃兔",
                            "藕",
                            "花生",
                            "毛豆",
                            "豆干"
                        ]
                    },
                    {
                        "sub_title":"火锅档口",
                        "text":[
                            "【汤底】",
                            "酸汤番茄汤底",
                            "冬阴功汤底 ",
                            "【小料】",
                            "葱花，花椒粉，白芝麻，辣椒面，小米椒，香油，香菜，蚝油，味精，鸡粉，蒜茸，香茅，芝麻酱 ",
                            "【荤菜】",
                            "鱿鱼须",
                            "目鱼花",
                            "肥牛",
                            "虾",
                            "蟹柳",
                            "素辽参",
                            "素乌参",
                            "虾饺 ",
                            "【素菜】",
                            "藕",
                            "青笋",
                            "土豆",
                            "海带",
                            "豆皮",
                            "龙口粉丝",
                            "金针菇",
                            "香菇",
                            "茼蒿",
                            "凤尾 ",
                            "娃娃菜"
                        ]
                    },
                    {
                        "sub_title":"蔬菜沙拉吧",
                        "text":[
                            "混合生菜",
                            "胡萝卜丝",
                            "圣女果",
                            "玉米粒",
                            "红腰豆",
                            "黄瓜",
                            "洋葱",
                            " "
                        ]
                    },
                    {
                        "sub_title":"钵钵鸡",
                        "text":[
                            "乐山钵钵鸡",
                            "红油钵钵鸡",
                            "椒麻钵钵鸡",
                            "怪味钵钵鸡",
                            "清汤钵钵鸡"
                        ]
                    },
                    {
                        "sub_title":"凉菜",
                        "text":[
                            "姜汁豇豆",
                            "红油脆笋",
                            "泡椒木耳",
                            "口水鸡",
                            "盐水鸭",
                            "干拌牛肉",
                            " "
                        ]
                    },
                    {
                        "sub_title":"海鲜／肉扒",
                        "text":[
                            "小鲳鱼",
                            "比目鱼",
                            "小黄鱼",
                            "秋刀鱼",
                            "牛排",
                            "鸡扒"
                        ]
                    },
                    {
                        "sub_title":"蒸档",
                        "text":[
                            "虾饺",
                            "烧卖",
                            "山药",
                            "玉米"
                        ]
                    },
                    {
                        "sub_title":"中西式热菜",
                        "text":[
                            "椒盐里脊",
                            "干锅牛蛙",
                            "海鲜蒸蛋",
                            "香菇什锦",
                            "蚝油菜心",
                            "新加坡烩海鲜",
                            "BBQ鸡翅/奥尔良鸡翅/卡真鸡翅",
                            "香茅虾锤/咖喱牛舌/炸猪扒配塔塔汁",
                            "五彩粒炒饭"
                        ]
                    },
                    {
                        "sub_title":"汤类",
                        "text":[
                            "西式例汤",
                            "中式例汤"
                        ]
                    },
                    {
                        "sub_title":"烤灯区",
                        "text":[
                            "披萨配小炸点"
                        ]
                    },
                    {
                        "sub_title":"水果档",
                        "text":[
                            "整水果／切片水果"
                        ]
                    },
                    {
                        "sub_title":"饮品类",
                        "text":[
                            "无酒精鸡尾酒",
                            "含酒精鸡尾酒",
                            "进口的红白葡萄酒",
                            "品牌啤酒",
                            "鲜榨西瓜汁",
                            "苹果汁",
                            "橙汁",
                            "西柚汁",
                            "可口可乐",
                            "雪碧",
                            "汤力水",
                            "王老吉",
                            "咖啡",
                            "红茶",
                            "绿茶"
                        ]
                    },
                    {
                        "sub_title":"甜品",
                        "text":[
                            "舒芙蕾",
                            "芝士蛋糕",
                            "歌剧蛋糕",
                            "水果塔",
                            "法式香草奶油焗蛋羹",
                            "巧克力布郎尼",
                            "意大利奶冻杯",
                            "榴莲千层",
                            "镜面慕斯蛋糕",
                            "巧克力喷泉",
                            "巧克力冰淇淋",
                            "香草冰淇淋",
                            "抹茶冰淇淋",
                            "草莓冰淇淋",
                            "冰淇林小料"
                        ]
                    },
                    {
                        "sub_title":"面包",
                        "text":[
                            "切片面包",
                            "杂粮包",
                            "法棍",
                            "小法包",
                            "软包"
                        ]
                    }
                ]
            },
            "id":6,
            "index":3
        },
        {
            "compatibility_policy":{
                "alert_message":"当前应用版本太低",
                "policy":"alert"
            },
            "data":{
                "lights":[
                    {
                        "content":"本次东方广场假日酒店蚝虾啤酒夜特别推出四款热辣美味的小龙虾可供客人选择，两款热食香辣和蒜蓉味，两款冷食香卤和油焖，满足食客的不同需求。香辣入味的小龙虾和沁爽啤酒相配，绝对算是虚度炎炎夏日的绝佳选择。",
                        "img_url":"https://image.ricebook.com/business/20693065823304",
                        "title":"四款小龙虾任选 共赴热辣啤酒之夜"
                    },
                    {
                        "content":"多彩而可爱的甜品区新增多款日式甜品，造型可爱的和果子、晶莹剔透，犹如水滴一般的水信玄饼，还有一处童话般的景色，就是汩汩流动的巧克力喷泉。香浓的巧克力酱裹挟着甜蜜的气息流泻而下，草莓、菠萝、西瓜等各式水果切块，拿竹签扎一块水果，轻轻伸到喷泉下，巧克力酱霎时将其包裹，外层甜蜜浓郁，水果清甜多汁，喜欢巧克力的人们恐怕要舍不得离开。",
                        "img_url":"https://image.ricebook.com/business/20366379523116",
                        "title":"多款和果子水信玄饼等日式甜品及巧克力喷泉"
                    }
                ],
                "text_array":[
                    "四款小龙虾任选 共赴热辣啤酒之夜",
                    "多款和果子水信玄饼等日式甜品及巧克力喷泉"
                ]
            },
            "id":4,
            "index":4
        },
        {
            "compatibility_policy":{
                "alert_message":"当前应用版本太低",
                "policy":"alert"
            },
            "data":{
                "contents":[
                    {
                        "text":"使用日期：2017.6.2-2017.9.30（七夕节不可使用）；"
                    },
                    {
                        "text":"使用时段：周三到周六 17:30-21:00；"
                    },
                    {
                        "text":"为避免高峰期建议至少提前1天提前预约；"
                    },
                    {
                        "text":"本产品支持随时退款； "
                    },
                    {
                        "text":"此礼遇不与店内其他优惠同享；"
                    },
                    {
                        "text":"如需开具发票，请具体咨询商户； "
                    },
                    {
                        "text":"如有疑问，请联系 ENJOY 客服。电话：4008-909-511；微信： enjoyricebook "
                    }
                ],
                "express":[

                ],
                "restaurant_phone_number":[
                    "028-61303751"
                ]
            },
            "id":9,
            "index":5
        },
        {
            "compatibility_policy":{
                "alert_message":"当前应用版本太低",
                "policy":"alert"
            },
            "data":{
                "recommend":[
                    {
                        "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRmluZm8lMkZwcm9kdWN0X2RldGFpbC5qc29uJTIyJTJDJTIyX3F1ZXJ5JTIyJTNBJTIyc3ViX3Byb2R1Y3RfaWQlM0Q1MDgyOTgwJTI2cHJvZHVjdF9pZCUzRDEwMzkzNDQlMjIlMkMlMjJfZnJvbSUyMiUzQSUyMnJlY29tbWVuZCUyMiUyQyUyMnByb2R1Y3RJZCUyMiUzQTEwNDU5NTklMkMlMjJfaW5kZXglMjIlM0EwJTdE",
                        "area_name":"红牌楼",
                        "desc":"生机食材 美味能量",
                        "distance":0,
                        "enjoy_url":"enjoyapp://product/detail?id=1045959",
                        "ext":{
                            "product_type":0,
                            "display_prop":[

                            ],
                            "light_spot":[
                                {
                                    "img":"21759863223708",
                                    "img_url":"https://image.ricebook.com/business/21759863223708",
                                    "title":"逃离城市森林 静享谧趣空间",
                                    "type":1,
                                    "content":"走进黑色与白色相搭配的门楣，穿越一片纵横交错的竹架，城市的喧嚣放佛已远在身后。浅灰色的墙壁、暖咖色地面、黑色桌椅和高脚凳，简单的黑白灰，低饱和度的色彩，Normann 等进口自丹麦家具，简约而低调的北欧风格，令人舒适而安心。The hideout in the city forest，就像一片隐藏在城市森林里的秘密空间，喝上一杯好喝的咖啡，抛却纷繁复杂的困扰，享受有趣而安静的人生片刻，让身心栖息在一个有趣的避风港。"
                                },
                                {
                                    "img":"21759865523664",
                                    "img_url":"https://image.ricebook.com/business/21759865523664",
                                    "title":"元气满满的能量轻食 ",
                                    "type":1,
                                    "content":"超级能量酸奶碗，以火遍健身圈的希腊酸奶为基底，奶香浓郁，高蛋白、低碳水、低钠且易饱腹。选用“健康网红”奇亚籽混合，轻松增加饱腹感、降低食欲。混合莓果、混合莓果、香蕉、燕麦、杏仁，酸甜可口、醇厚芳香的饱满滋味让立刻人元气满满。深海三明治选用新鲜厚切金枪鱼，肉质紧密，口感鲜嫩绵密，一口下去，冰鲜的口感放佛海风扑面而来。完美营养减脂色拉则是美好身材的最佳搭档，蛋白质含量可与牛肉媲美的藜麦搭配鸡胸肉、鸡蛋、玉米粒、苦菊、罗马生菜等食材，一大碗也能完全 hold 住，饱腹又美味。"
                                }
                            ]
                        },
                        "origin_price":8000,
                        "price":6600,
                        "product_id":1045959,
                        "product_image_url":"https://image.ricebook.com/business/21759858623704",
                        "product_name":"The Hideout 单人轻食餐",
                        "sell_state":1,
                        "show_entity_name":"位"
                    },
                    {
                        "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRmluZm8lMkZwcm9kdWN0X2RldGFpbC5qc29uJTIyJTJDJTIyX3F1ZXJ5JTIyJTNBJTIyc3ViX3Byb2R1Y3RfaWQlM0Q1MDgyOTgwJTI2cHJvZHVjdF9pZCUzRDEwMzkzNDQlMjIlMkMlMjJfZnJvbSUyMiUzQSUyMnJlY29tbWVuZCUyMiUyQyUyMnByb2R1Y3RJZCUyMiUzQTEwMDkzODglMkMlMjJfaW5kZXglMjIlM0ExJTdE",
                        "area_name":"高新区",
                        "desc":"佛山星级大厨礼备十余新款点心任选 ",
                        "distance":0,
                        "enjoy_url":"enjoyapp://product/detail?id=1009388",
                        "ext":{
                            "product_type":0,
                            "display_prop":[
                                {
                                    "background_color":"#f6f6f6",
                                    "name":"地铁沿线",
                                    "background_img_color":"red",
                                    "font_color":"#1a1a1a"
                                },
                                {
                                    "background_color":"#f6f6f6",
                                    "name":"城中招牌店",
                                    "background_img_color":"red",
                                    "font_color":"#1a1a1a"
                                }
                            ],
                            "light_spot":[
                                {
                                    "img":"21224402923220",
                                    "img_url":"https://image.ricebook.com/business/21224402923220",
                                    "title":"经典粤式味道 川韵灵犀一笔",
                                    "type":1,
                                    "content":"成都希尔顿酒店御玺中餐厅阅如其名，典雅大方，空间通透明亮。简洁古朴的装潢背景，再糅入川西古韵一点灵犀之光，顷刻间便能捕捉到食客风雅之情。而餐厅点心更是由厨师团队精心打造，多年甜品制作的千锤百炼融入匠心独运的巧思，将每一道餐点呈上客人心间。入厅，便觉百味飘香；入口，更是口齿生香。"
                                },
                                {
                                    "img":"17516357123606",
                                    "img_url":"https://image.ricebook.com/business/17516357123606",
                                    "title":"八十余款中式点心任选 从熊猫流沙包到蜜汁叉烧各式美味齐备",
                                    "type":1,
                                    "content":"希尔顿酒店御玺中餐厅环境典雅，空间通透明亮，各式川粤点心与地道川菜皆有。蓉城味道里的「宫保鸡丁」「油焖虎皮青椒」鲜辣开胃，蒸点流沙包摇身一变，化成憨态可掬又可爱的熊猫模样。内馅儿带有颗粒感的流淌着浓香，一个熊猫的样子就颇具成都味道。「榴莲酥」外形像奇异果，酥皮脆口，内里却是软糯的榴莲，口齿留香。"
                                }
                            ]
                        },
                        "origin_price":16000,
                        "price":14800,
                        "product_id":1009388,
                        "product_image_url":"https://image.ricebook.com/business/21178875023735",
                        "product_name":"希尔顿·御玺中餐厅主厨点心节午市点心自助",
                        "sell_state":1,
                        "show_entity_name":"位"
                    },
                    {
                        "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRmluZm8lMkZwcm9kdWN0X2RldGFpbC5qc29uJTIyJTJDJTIyX3F1ZXJ5JTIyJTNBJTIyc3ViX3Byb2R1Y3RfaWQlM0Q1MDgyOTgwJTI2cHJvZHVjdF9pZCUzRDEwMzkzNDQlMjIlMkMlMjJfZnJvbSUyMiUzQSUyMnJlY29tbWVuZCUyMiUyQyUyMnByb2R1Y3RJZCUyMiUzQTEwNDY1MzIlMkMlMjJfaW5kZXglMjIlM0EyJTdE",
                        "area_name":"玉林",
                        "desc":"老板跋山涉水寻找正宗羊肉",
                        "distance":0,
                        "enjoy_url":"enjoyapp://product/detail?id=1046532",
                        "ext":{
                            "product_type":0,
                            "display_prop":[

                            ],
                            "light_spot":[
                                {
                                    "img":"20123161723863",
                                    "img_url":"https://image.ricebook.com/business/20123161723863",
                                    "title":"简洁工业风 蓝调的渲染下慵懒得不像一家烧烤店",
                                    "type":1,
                                    "content":"一串不肯媚俗的位于玉林东路，在周围一圈老式餐厅中，以其新式装修和招牌显得格外瞩目。店内装饰主打工业风，暖黄色的灯光和水泥色的墙面给人简约之感。相比成都其他的烧烤店，一串不肯媚俗的没有觥筹交错的喧嚣，反而是听着蓝调，慵懒地窝在沙发里啃肉串的舒适。"
                                },
                                {
                                    "img":"20123169123992",
                                    "img_url":"https://image.ricebook.com/business/20123169123992",
                                    "title":"因为不肯媚俗 所以跋山涉水寻找巴什拜羔羊肉",
                                    "type":1,
                                    "content":"有人曾质疑老板的羊肉是否来自正宗的原产地，老板则特别肯定地说，自己曾用了10个月走遍大半个中国，从西南深山到蒙西草原，走遍了所有绵羊养殖区，尝遍了三十多种绵羊，最后只挑选来自新疆库鲁斯台草原原始牧场的巴什拜羔羊，冷链直运到成都。他认为不同的羊肉有不同的吃法，比如内蒙古大草原的羊肉适合涮锅，而只有新疆的这种羊肉才适合做烧烤，烤出来的肉味才能达到上乘。还有店内的米酒、蘸碟里的香料等，也是老板从东北深山发掘，带到成都，做一家以东北味儿为基础的烧烤店。"
                                },
                                {
                                    "img":"20123170823865",
                                    "img_url":"https://image.ricebook.com/business/20123170823865",
                                    "title":"不仅仅是羊肉串 其他烤串同样惊喜",
                                    "type":1,
                                    "content":"店内除了招牌的烤羊肉串，其他的烤串也都不肯媚俗。罗脊肉即我们常说的猪的护心肉，虽然是瘦肉，但是吃起来仍然有肥肉细嫩的口感，烤制之后蘸着味碟入口，香而不腻。熔浆面包则是面包片包裹着棉花糖，在经过炭火的熏烤后，面包酥脆，棉花糖也随高温熔化而软糯绵长，令食客的内心都柔软下来，是一份治愈人心的烤串。"
                                }
                            ]
                        },
                        "origin_price":36800,
                        "price":28800,
                        "product_id":1046532,
                        "product_image_url":"https://image.ricebook.com/business/20123158723859",
                        "product_name":"一串不肯媚俗的灵魂四人膻",
                        "sell_state":1,
                        "show_entity_name":"4位"
                    },
                    {
                        "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRmluZm8lMkZwcm9kdWN0X2RldGFpbC5qc29uJTIyJTJDJTIyX3F1ZXJ5JTIyJTNBJTIyc3ViX3Byb2R1Y3RfaWQlM0Q1MDgyOTgwJTI2cHJvZHVjdF9pZCUzRDEwMzkzNDQlMjIlMkMlMjJfZnJvbSUyMiUzQSUyMnJlY29tbWVuZCUyMiUyQyUyMnByb2R1Y3RJZCUyMiUzQTEwMDk4ODYlMkMlMjJfaW5kZXglMjIlM0EzJTdE",
                        "area_name":"盐市口",
                        "desc":"ENJOY 赠送调制精油和精油吊坠",
                        "distance":0,
                        "enjoy_url":"enjoyapp://product/detail?id=1009886",
                        "ext":{
                            "product_type":0,
                            "display_prop":[

                            ],
                            "light_spot":[
                                {
                                    "img":"17541782323418",
                                    "img_url":"https://image.ricebook.com/business/17541782323418",
                                    "title":"技术手法操作流程均为泰国 SPA 国际专业标准",
                                    "type":1,
                                    "content":"禅庭 SPA 是内陆唯一泰国 SPA Thai Spa Association 协会会员单位。禅庭的技术手法、操作流程均参考了泰国 SPA 协会的国际化专业标准，同时也结合了本地特点，独创七轮 Chakras 芳香身心调整与经络理疗相结合的疗愈体系。在疗程体系中运用植物芳香精油、喜马拉雅颂钵、经络疏通仪器 、艾灸仪、细胞激活仪等以及非常丰富的按摩手法。"
                                },
                                {
                                    "img":"17541788823385",
                                    "img_url":"https://image.ricebook.com/business/17541788823385",
                                    "title":"适合怀孕16周至38周健康孕妇的舒压按摩护理",
                                    "type":1,
                                    "content":"此次礼遇中的单人妊娠舒压按摩护理，适合怀孕16周至38周健康孕妇。护理之初，SPA 顾问会先了解孕期妈妈的身体情况，根据身体情况专门调配按摩油，浴足放松后，用来自喜玛拉雅手工铸造铜质密宗颂钵，以特定的节率敲击钵体，沉稳悠远的声音放松身心。天然的植物精油配合舒适的手法，为怀孕的妈妈滋养肌肤、调节情绪、改善妊娠中的心烦、倦怠、腰酸背痛、四肢水肿等情况。"
                                },
                                {
                                    "img":"17541791813489",
                                    "img_url":"https://image.ricebook.com/business/17541791813489",
                                    "title":"十多种名贵中药加一小时纯手法蜜蜡按摩",
                                    "type":1,
                                    "content":"百草五行瘦身中禅庭 SPA 加入了10多种名贵的中药。禅庭最开始用它来调理身体，在调理身体的过程中发现有减肥的效果，才用来减肥。曾经在研究所做过无毒实验，小白鼠大剂量吃了也没有任何问题。在减肥的过程中，会有养生的功效，能够改善脾胃，肠道，血压血脂，泌尿生殖系统，水肿及代谢缓慢等问题。哺乳期，月经期均可做。"
                                }
                            ]
                        },
                        "origin_price":68000,
                        "price":23800,
                        "product_id":1009886,
                        "product_image_url":"https://image.ricebook.com/business/17541757113578",
                        "product_name":"禅庭舒缓按摩单人餐",
                        "sell_state":1,
                        "show_entity_name":"位"
                    },
                    {
                        "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRmluZm8lMkZwcm9kdWN0X2RldGFpbC5qc29uJTIyJTJDJTIyX3F1ZXJ5JTIyJTNBJTIyc3ViX3Byb2R1Y3RfaWQlM0Q1MDgyOTgwJTI2cHJvZHVjdF9pZCUzRDEwMzkzNDQlMjIlMkMlMjJfZnJvbSUyMiUzQSUyMnJlY29tbWVuZCUyMiUyQyUyMnByb2R1Y3RJZCUyMiUzQTEwMjU1NDklMkMlMjJfaW5kZXglMjIlM0E0JTdE",
                        "area_name":"春熙路",
                        "desc":"尽享星级酒店的下午茶点",
                        "distance":0,
                        "enjoy_url":"enjoyapp://product/detail?id=1025549",
                        "ext":{
                            "product_type":0,
                            "display_prop":[

                            ],
                            "light_spot":[
                                {
                                    "img":"19241590123773",
                                    "img_url":"https://image.ricebook.com/business/19241590123773",
                                    "title":"超多经典粤式点心菜品任意选择",
                                    "type":1,
                                    "content":"NICCOLO 玥轩的菜单，让喜爱粤点的食客惊喜不已，菜单不仅有「奶黄流沙包」、「蚝皇叉烧包」等地到粤式点心，还有「麻香头抽龙芽炒面」、「生滚牛肉粥」等风味小吃，多款精挑细选过的点心主食，几乎都能找到各自的心头好。"
                                },
                                {
                                    "img":"17118216613259",
                                    "img_url":"https://image.ricebook.com/business/17118216613259",
                                    "title":"与商场互通的星级酒店 逛完街再吃顿好的",
                                    "type":1,
                                    "content":"NICCOLO 坐落于 IFS 金融中心，玥轩餐厅的入口与商场互通，虽是星级酒店的餐饮，逛完街便能随时进入吃顿品质午餐。"
                                },
                                {
                                    "img":"17118219313471",
                                    "img_url":"https://image.ricebook.com/business/17118219313471",
                                    "title":"每一款菜品都是现做现吃",
                                    "type":1,
                                    "content":"玥轩餐厅的包点都是现点现做。新鲜是任何调味品都无法调适出的自然之味。「蚝皇叉烧包」碳烤过后的肉有些美好的焦香味，肉汁本身的醇厚被底下垫着的葱丝吸收了些许油腻，多了些清香。「烧汁珍菌蘑菇包」菌菇的特殊香气在特制的酱汁的浇淋下别具一格。"
                                }
                            ]
                        },
                        "origin_price":10600,
                        "price":7800,
                        "product_id":1025549,
                        "product_image_url":"https://image.ricebook.com/business/19241544923948",
                        "product_name":"Niccolo·玥轩周末单人下午茶点心自助",
                        "sell_state":1,
                        "show_entity_name":"位"
                    },
                    {
                        "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRmluZm8lMkZwcm9kdWN0X2RldGFpbC5qc29uJTIyJTJDJTIyX3F1ZXJ5JTIyJTNBJTIyc3ViX3Byb2R1Y3RfaWQlM0Q1MDgyOTgwJTI2cHJvZHVjdF9pZCUzRDEwMzkzNDQlMjIlMkMlMjJfZnJvbSUyMiUzQSUyMnJlY29tbWVuZCUyMiUyQyUyMnByb2R1Y3RJZCUyMiUzQTEwNDUxNTQlMkMlMjJfaW5kZXglMjIlM0E1JTdE",
                        "area_name":"高新区",
                        "desc":"西部第一家费尔蒙酒店",
                        "distance":0,
                        "enjoy_url":"enjoyapp://product/detail?id=1045154",
                        "ext":{
                            "product_type":0,
                            "display_prop":[

                            ],
                            "light_spot":[
                                {
                                    "img":"20005527723263",
                                    "img_url":"https://image.ricebook.com/business/20005527723263",
                                    "title":"海鲜活当先",
                                    "type":1,
                                    "content":"亲眼所见，亲手挑选喜爱鲜物是品尝海鲜的一大趣味所在。将海鲜夜市的游水海鲜池搬到五星级酒店内，现选鲜烹，生活气息浓厚而不市井。从游水海鲜池中直捞上案板，蒸、烤、焗、烩，顷刻完成。从活到熟，迅速转变，鲜味锁于盘中，配以国际风味调味酱汁直送餐桌，片时可享。"
                                },
                                {
                                    "img":"20005531623265",
                                    "img_url":"https://image.ricebook.com/business/20005531623265",
                                    "title":"丰富海鲜品种应时节而变",
                                    "type":1,
                                    "content":" “成都美食站”特供鲜活麻辣小龙虾，以四川之味鲜调爆炒，献给本地老饕。应时令供应半人长的澳洲大龙虾，波士顿龙虾，老虎斑，多宝鱼等鲜活品种。冷餐台长供阿拉斯加长脚蟹，新西兰青口与沿海鲜送扇贝等各式丰富海鲜。除了独享海味，还有鲜货配以时蔬与特色酱汁的泰式意式料理，丰富层次味漫舌尖。最具特色的是莳萝腌三文鱼与四川辣椒腌三文鱼，将北欧风味与四川风味双重概念同时呈现，碰撞出热烈火花。 "
                                }
                            ]
                        },
                        "origin_price":41800,
                        "price":36800,
                        "product_id":1045154,
                        "product_image_url":"https://image.ricebook.com/business/20005514523081",
                        "product_name":"费尔蒙酒店·Spectrum 食百绚海鲜夜市单人自助晚餐",
                        "sell_state":1,
                        "show_entity_name":"位"
                    },
                    {
                        "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRmluZm8lMkZwcm9kdWN0X2RldGFpbC5qc29uJTIyJTJDJTIyX3F1ZXJ5JTIyJTNBJTIyc3ViX3Byb2R1Y3RfaWQlM0Q1MDgyOTgwJTI2cHJvZHVjdF9pZCUzRDEwMzkzNDQlMjIlMkMlMjJfZnJvbSUyMiUzQSUyMnJlY29tbWVuZCUyMiUyQyUyMnByb2R1Y3RJZCUyMiUzQTEwMDc3NDUlMkMlMjJfaW5kZXglMjIlM0E2JTdE",
                        "area_name":"春熙路",
                        "desc":"一次品尝四种口味裸蛋糕",
                        "distance":0,
                        "enjoy_url":"enjoyapp://product/detail?id=1007745",
                        "ext":{
                            "product_type":1,
                            "display_prop":[

                            ],
                            "light_spot":[
                                {
                                    "img":"17401758113676",
                                    "img_url":"https://image.ricebook.com/business/17401758113676",
                                    "title":"四种清新自然的裸蛋糕 寓意美好的新鲜口味",
                                    "type":1,
                                    "content":"MOMOKO 春四季裸蛋糕包含四种清新自然口味：法国纯脂巧克力和芝士奶油夹心制作的乳酪味浓郁的浆果阵地，拥有红豆夹心清爽酸甜的抹茶戚风蛋糕，柑橘丁夹心入口 Q 弹的柠檬柑橘戚风蛋糕，还有触动少女心的粉红马蒂尼，每一款都是人气之选。"
                                },
                                {
                                    "img":"17401759423520",
                                    "img_url":"https://image.ricebook.com/business/17401759423520",
                                    "title":"天然食材 浪漫风格 每一款四季都有自己的故事",
                                    "type":1,
                                    "content":"此次的春四季将马卡龙、草莓、红豆、巧克力、蓝莓等等天然食材组合在一起，裸露的水果装点其上，入口清爽，如沐春风。浪漫的情调不觉在口中萦绕。MOMOKO 的每一款四季都有自己的故事。如春四季，寓意美好。"
                                }
                            ]
                        },
                        "origin_price":25800,
                        "price":25200,
                        "product_id":1007745,
                        "product_image_url":"https://image.ricebook.com/business/17401753213725",
                        "product_name":"MOMOKO 蜜桃家四季蛋糕",
                        "sell_state":1,
                        "show_entity_name":"份"
                    },
                    {
                        "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRmluZm8lMkZwcm9kdWN0X2RldGFpbC5qc29uJTIyJTJDJTIyX3F1ZXJ5JTIyJTNBJTIyc3ViX3Byb2R1Y3RfaWQlM0Q1MDgyOTgwJTI2cHJvZHVjdF9pZCUzRDEwMzkzNDQlMjIlMkMlMjJfZnJvbSUyMiUzQSUyMnJlY29tbWVuZCUyMiUyQyUyMnByb2R1Y3RJZCUyMiUzQTEwNTEwODMlMkMlMjJfaW5kZXglMjIlM0E3JTdE",
                        "area_name":"桐梓林",
                        "desc":"坚持”纯然、手感” 不添加色素的健康蛋糕",
                        "distance":0,
                        "enjoy_url":"enjoyapp://product/detail?id=1051083",
                        "ext":{
                            "product_type":1,
                            "display_prop":[

                            ],
                            "light_spot":[
                                {
                                    "img":"22735024523205",
                                    "img_url":"https://image.ricebook.com/business/22735024523205",
                                    "title":"超模 Linda 也爱吃的低糖低油低脂蛋糕",
                                    "type":1,
                                    "content":"Hi Bake 的蛋糕因为低糖低油低脂，并且顺应“健康烘焙”的理念。使传统烘焙产品含糖量从 40%-45% 降低到 15%-20% 。在低脂的基础上又使油脂含量从 30%-40% 降低到 10% 以下。所以就连超模 Linda 也爱上了 Hi Bake 的蛋糕。"
                                },
                                {
                                    "img":"22731847623083",
                                    "img_url":"https://image.ricebook.com/business/22731847623083",
                                    "title":"坚持”纯然、手感” 不添加色素的健康蛋糕",
                                    "type":1,
                                    "content":"在不改变Hi bake一直坚持的“纯然、手感”理念下，「布朗熊蛋糕」选用新西兰进口乳脂奶油，无天然色素，蛋糕胚中含有新鲜制作的芒果布丁夹层，更加迎合小朋友的口感。蛋糕上面的装饰是无毒灭菌的卡通公仔，做出最能瞬间吸引孩子眼球的造型，虽不能食用，但可以作为玩具陪伴孩子玩耍。"
                                },
                                {
                                    "img":"20269801723380",
                                    "img_url":"https://image.ricebook.com/business/20269801723380",
                                    "title":"甜度减半热量仅为普通的十分之一的「生乳半糖牛轧糖」",
                                    "type":1,
                                    "content":"此次礼遇中的「生乳半糖牛轧糖」采用有机花生仁和新西兰安佳奶粉制作，历经半年研发，半年调整，12道工艺磨砺，日本海藻糖代替蔗糖，甜度减半，热量仅为普通的十分之一，好吃不粘牙，坚韧香脆，奶香浓郁。桔柑和麦麸提炼的环保纸浆的包装，环保又美观。"
                                }
                            ]
                        },
                        "origin_price":20600,
                        "price":16800,
                        "product_id":1051083,
                        "product_image_url":"https://image.ricebook.com/business/22731818723077",
                        "product_name":"Hi bake儿童少女系蛋糕3选1+生乳牛轧糖套餐",
                        "sell_state":1,
                        "show_entity_name":"份"
                    },
                    {
                        "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRmluZm8lMkZwcm9kdWN0X2RldGFpbC5qc29uJTIyJTJDJTIyX3F1ZXJ5JTIyJTNBJTIyc3ViX3Byb2R1Y3RfaWQlM0Q1MDgyOTgwJTI2cHJvZHVjdF9pZCUzRDEwMzkzNDQlMjIlMkMlMjJfZnJvbSUyMiUzQSUyMnJlY29tbWVuZCUyMiUyQyUyMnByb2R1Y3RJZCUyMiUzQTEwNDgyOTclMkMlMjJfaW5kZXglMjIlM0E4JTdE",
                        "area_name":"科华北路",
                        "desc":"零添加的手工精制甜点",
                        "distance":0,
                        "enjoy_url":"enjoyapp://product/detail?id=1048297",
                        "ext":{
                            "product_type":1,
                            "display_prop":[

                            ],
                            "light_spot":[
                                {
                                    "img":"22196522923744",
                                    "img_url":"https://image.ricebook.com/business/22196522923744",
                                    "title":"以自然的食材还原真实的感动",
                                    "type":1,
                                    "content":"吾卷是成都并不多见的蛋糕卷专卖店，专注于提供“纯手工无添加”的高颜值蛋糕卷。餐厅精选新西兰安佳动物乳脂奶油、日本丸久小山园抹茶粉、法国Valrhona 巧克力可可粉等进口食材，以优质原料缔造最佳的口感。吾卷坚持古法手工作业，拒绝工业化加工，以传统制作手法寻找食物最好的口感；坚持“零添加”理念，蛋糕卷上的颜色都是从新鲜食材中提取的，例如绿色来自抹茶、粉色来自覆盆子果泥，深棕来自巧克力。分享健康与美味是创立品牌的初衷，要依靠食材自身的特性和的传统的手工工艺，还原出食材的本真滋味，带给食客最纯真的美好。"
                                },
                                {
                                    "img":"22196527323727",
                                    "img_url":"https://image.ricebook.com/business/22196527323727",
                                    "title":"纯正宇治抹茶粉与香醇奶油的邂逅",
                                    "type":1,
                                    "content":"吾卷使用的抹茶粉均来自宇治老字号品牌丸久小山园，作为宇治市久负盛名的茶园之一的小山园一向以出产高品质抹茶而著称。「宇治抹茶蜜豆」拥有天使般柔软口感，戚风蛋糕松软黏绵，轻咬一口，抹茶的甘苦味便在嘴边四散开来；内部包裹的铁塔淡奶油奶香浓郁，入口即化，清爽而不甜腻；内馅蜜豆颗粒圆润饱满，软糯香甜。抹茶的清苦、奶油的幼滑和红豆的甜糯巧妙舒适的融为一体，一口倾心。"
                                },
                                {
                                    "img":"22196526023802",
                                    "img_url":"https://image.ricebook.com/business/22196526023802",
                                    "title":"一见钟情不如久吃不腻",
                                    "type":1,
                                    "content":"吾卷精益求精，追求一种甜而不腻的完美口感。在不影响食物味道的基础上对配方进行改良，将糖分含量减少50%，并且尽可能地用蜂蜜替代砂糖。吃起来口感轻盈、甜而不腻。吾卷制作的低脂低糖的甜点，解决了糖分过高的问题，让食客能够卸下这“甜蜜的负担”，肆意享受甜食带来的幸福与满足。"
                                }
                            ]
                        },
                        "origin_price":21800,
                        "price":20800,
                        "product_id":1048297,
                        "product_image_url":"https://image.ricebook.com/business/22196500523740",
                        "product_name":"吾卷乳酪慕斯蛋糕/鲜果奶油蛋糕",
                        "sell_state":1,
                        "show_entity_name":"份"
                    },
                    {
                        "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRmluZm8lMkZwcm9kdWN0X2RldGFpbC5qc29uJTIyJTJDJTIyX3F1ZXJ5JTIyJTNBJTIyc3ViX3Byb2R1Y3RfaWQlM0Q1MDgyOTgwJTI2cHJvZHVjdF9pZCUzRDEwMzkzNDQlMjIlMkMlMjJfZnJvbSUyMiUzQSUyMnJlY29tbWVuZCUyMiUyQyUyMnByb2R1Y3RJZCUyMiUzQTEwNDc0MDclMkMlMjJfaW5kZXglMjIlM0E5JTdE",
                        "area_name":"双林路",
                        "desc":"幸福就是唇齿之间的那一丝甜",
                        "distance":0,
                        "enjoy_url":"enjoyapp://product/detail?id=1047407",
                        "ext":{
                            "product_type":1,
                            "display_prop":[

                            ],
                            "light_spot":[
                                {
                                    "img":"22114173423279",
                                    "img_url":"https://image.ricebook.com/business/22114173423279",
                                    "title":"每一颗元生牛轧糖 都是儿时的记忆",
                                    "type":1,
                                    "content":"牛轧糖是许多人儿时的回忆，它那奶味醇厚、软糯香甜的味道让人念念不忘。元生采用法国进口黄油、新西兰优质奶粉及日本天然海藻糖等原材料，高达60%的杏仁比例，再经过手工精制，唇齿之间满是香甜细腻，口感香软不失嚼劲。每一批次的牛轧糖从处理配料，下锅熬煮，起锅到成型，皆以最古老的手工技法保存食物最本来的风味，找回儿时初尝时的甜蜜与幸福。咬下一口，立马被浓郁酥脆奶香所包裹，伴随着酥脆的坚果和缠绵坚实的咀嚼，幸福便在那一刻悄悄降临。"
                                },
                                {
                                    "img":"22114175623280",
                                    "img_url":"https://image.ricebook.com/business/22114175623280",
                                    "title":"以海南凤梨入馅的酥软凤梨酥 ",
                                    "type":1,
                                    "content":"凤梨酥起源于三国时期，相传当年刘备以凤梨入馅制成的喜饼迎娶孙权之妹。后来逐渐演变为结合西式派皮与中式馅料所制成的现代“凤梨酥”，外皮酥松化口，凤梨内馅甜而不腻。元生精选甜如蜜、香如花的海南菠萝，从去皮、切丁、再经历两小时的手工煎熬和搅拌，每一个环节都经过严格把控和标准化制作。内陷无其他添加物，仅加入蜂蜜与砂糖调味，保留住凤梨最原始的酸甜滋味。轻咬一口，果香四溢，酥到心甜。"
                                }
                            ]
                        },
                        "origin_price":2500,
                        "price":2300,
                        "product_id":1047407,
                        "product_image_url":"https://image.ricebook.com/business/22114158623332",
                        "product_name":"元生咖啡特制牛轧糖/凤梨酥",
                        "sell_state":1,
                        "show_entity_name":"份"
                    }
                ]
            },
            "id":12,
            "index":9999
        }
    ],
    "basic":{
        "description":"融汇多国菜系的 fusion restaurant",
        "display_property_group":[

        ],
        "is_favorite":false,
        "is_flash":false,
        "left_count":4649,
        "max_count_per_order":100,
        "min_count_per_order":1,
        "name":"BISHOP 主教餐吧双人餐",
        "offline_time":1506787140000,
        "origin_price":18400,
        "price":13800,
        "product_id":1041327,
        "product_images":[{"img_url":"https://image.ricebook.com/business/20969581423536","special_show":false},{"img_url":"https://image.ricebook.com/business/20969588123537","special_show":false},{"img_url":"https://image.ricebook.com/business/20969588423454","special_show":false},{"img_url":"https://image.ricebook.com/business/20969588223453","special_show":false},{"img_url":"https://image.ricebook.com/business/20969588323509","special_show":false},{"img_url":"https://image.ricebook.com/business/20969588323508","special_show":false},{"img_url":"https://image.ricebook.com/business/20969588223507","special_show":false},{"img_url":"https://image.ricebook.com/business/20969588123538","special_show":false},{"img_url":"https://image.ricebook.com/business/21109329223073","special_show":false},{"img_url":"https://image.ricebook.com/business/21108811523027","special_show":false},{"img_url":"https://image.ricebook.com/business/20927080423414","special_show":false},{"img_url":"https://image.ricebook.com/business/21108811523132","special_show":false},{"img_url":"https://image.ricebook.com/business/20927079723413","special_show":false}],
        "product_type":0,
        "refund_type":2,
        "sell_begin_time":1496332800000,
        "sell_end_time":1506787140000,
        "sell_state":5,
        "server_time":1521003432140,
        "share_info":{
            "sub_title":"分享赢礼券",
            "text":"好友从你分享的链接注册 ENJOY 并消费，你可获得价值 50 元礼券，多邀多得。"
        },
        "shelving_time":1496332800000,
        "short_name":"东方广场假日酒店蜀咖啡蚝虾啤酒夜单人自助晚餐",
        "show_entity_name":"位",
        "spec":"蚝虾啤酒夜成人自助",
        "sub_product_array":[
            {
                "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRmluZm8lMkZwcm9kdWN0X2RldGFpbC5qc29uJTIyJTJDJTIyX3F1ZXJ5JTIyJTNBJTIyc3ViX3Byb2R1Y3RfaWQlM0Q1MDgyOTgwJTI2cHJvZHVjdF9pZCUzRDEwMzkzNDQlMjIlMkMlMjJfaW5kZXglMjIlM0EwJTJDJTIyc3ViUHJvZHVjdElkJTIyJTNBNTA4Mjk4MCU3RA==",
                "is_flash":false,
                "is_promotion":false,
                "name":"东方广场假日酒店蜀咖啡蚝虾啤酒夜单人自助晚餐",
                "origin_price":25800,
                "pass_info":[

                ],
                "price":13900,
                "sell_state":5,
                "show_entity_name":"位",
                "spec":"蚝虾啤酒夜成人自助",
                "sub_product_id":5082980
            },
            {
                "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRmluZm8lMkZwcm9kdWN0X2RldGFpbC5qc29uJTIyJTJDJTIyX3F1ZXJ5JTIyJTNBJTIyc3ViX3Byb2R1Y3RfaWQlM0Q1MDgyOTgwJTI2cHJvZHVjdF9pZCUzRDEwMzkzNDQlMjIlMkMlMjJfaW5kZXglMjIlM0ExJTJDJTIyc3ViUHJvZHVjdElkJTIyJTNBNTA4Mjk4MSU3RA==",
                "is_flash":false,
                "is_promotion":false,
                "name":"东方广场假日酒店蜀咖啡蚝虾啤酒夜单人自助晚餐",
                "pass_info":[

                ],
                "price":9800,
                "sell_state":5,
                "show_entity_name":"位",
                "spec":"蚝虾啤酒夜儿童自助",
                "sub_product_id":5082981
            }
        ],
        "sub_product_id":5082980
    }
}
                  axios.post('/api/savedetail',pro)
                        .then(function(res){
                            console.log(res)
                        })
            }





		}
	}


</script>
<style></style>



