<template>
	<div>
		admin

		<button @click="getcitydatas">indexdata</button>
            <br>
            <br>
            <br>
            <br>
        <button @click="getFindCarousel">getFindCarousel</button>

            <br>
            <br>
            <br>
        <button @click='savedetails'>savwdetails</button>


	</div>


</template>


<script>
import axios from 'axios'

export default{
	methods:{
		
		getcitydatas(){
			var pro ={
        "group_section":{
            "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRnYxJTJGd2ViJTJGd2Vla19jaG9pY2UuanNvbiUyMiUyQyUyMl9xdWVyeSUyMiUzQSUyMnBhZ2UlM0QwJTI2Y2l0eV9pZCUzRDIzNSUyMiUyQyUyMnRpdGxlJTIyJTNBJTIyJUU2JUFGJThGJUU1JTkxJUE4JUU3JUIyJUJFJUU5JTgwJTg5JUU5JUE0JTkwJUU5JUE1JUFFJTIyJTdE",
            "desc":"8月7日更新",
            "title":"每周精选餐饮"
        },
        "tabs":[
            {
                "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRnYxJTJGd2ViJTJGd2Vla19jaG9pY2UuanNvbiUyMiUyQyUyMl9xdWVyeSUyMiUzQSUyMnBhZ2UlM0QwJTI2Y2l0eV9pZCUzRDIzNSUyMiUyQyUyMnByaWNlJTIyJTNBJTIyMTM5JTIyJTJDJTIyaWQlMjIlM0ElMjI1MDgyOTgwJTIyJTJDJTIydGl0bGUlMjIlM0ElMjIlRTQlQjglOUMlRTYlOTYlQjklRTUlQjklQkYlRTUlOUMlQkElRTUlODElODclRTYlOTclQTUlRTklODUlOTIlRTUlQkElOTclRTglOUMlODAlRTUlOTIlOTYlRTUlOTUlQTElRTglOUElOUQlRTglOTklQkUlRTUlOTUlQTQlRTklODUlOTIlRTUlQTQlOUMlRTUlOEQlOTUlRTQlQkElQkElRTglODclQUElRTUlOEElQTklRTYlOTklOUElRTklQTQlOTAlMjIlMkMlMjJ0eXBlJTIyJTNBJTIycHJvZHVjdCUyMiUyQyUyMmVuam95VXJsJTIyJTNBJTIyZW5qb3lhcHAlM0ElMkYlMkZwcm9kdWN0JTJGZGV0YWlsJTNGaWQlM0QxMDM5MzQ0JTI2c3ViLXByb2R1Y3QtaWQlM0Q1MDgyOTgwJTIyJTdE",
                "desc":"尽享鲜虾生蚝盛宴",
                "enjoy_url":"enjoyapp://product/detail?id=1039344&sub-product-id=5082980",
                "entity_name":"位",
                "ext":{
                    "product_type":0
                },
                "group":false,
                "id":"5082980",
                "original_price":"¥258",
                "price":"139",
                "tag":"春熙路",
                "title":"东方广场假日酒店蜀咖啡蚝虾啤酒夜单人自助晚餐",
                "type":"product",
                "url":"https://image.ricebook.com/business/20693050723276",
                "url_type":"image"
            },
            {
                "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRnYxJTJGd2ViJTJGd2Vla19jaG9pY2UuanNvbiUyMiUyQyUyMl9xdWVyeSUyMiUzQSUyMnBhZ2UlM0QwJTI2Y2l0eV9pZCUzRDIzNSUyMiUyQyUyMnByaWNlJTIyJTNBJTIyMTI4JTIyJTJDJTIyaWQlMjIlM0ElMjI1MDg5NjA1JTIyJTJDJTIydGl0bGUlMjIlM0ElMjJWSU5PVEVLQSVFNiVCMyU5NSVFNSVCQyU4RiVFNyU4MyVBNCVFOCU4MiU4OSVFNSU4RCU5NSVFNyU4MiVCOSVFNSVCQyU4RiVFOCU4NyVBQSVFNSU4QSVBOSUyMiUyQyUyMnR5cGUlMjIlM0ElMjJwcm9kdWN0JTIyJTJDJTIyZW5qb3lVcmwlMjIlM0ElMjJlbmpveWFwcCUzQSUyRiUyRnByb2R1Y3QlMkZkZXRhaWwlM0ZpZCUzRDEwNDI0MDQlMjZzdWItcHJvZHVjdC1pZCUzRDUwODk2MDUlMjIlN0Q=",
                "desc":"法式烤肉与美酒畅享",
                "enjoy_url":"enjoyapp://product/detail?id=1042404&sub-product-id=5089605",
                "entity_name":"位",
                "ext":{
                    "product_type":0
                },
                "group":false,
                "id":"5089605",
                "original_price":"¥158",
                "price":"128",
                "tag":"春熙路",
                "title":"VINOTEKA法式烤肉单点式自助",
                "type":"product",
                "url":"https://image.ricebook.com/business/21164538023864",
                "url_type":"image"
            },
            {
                "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRnYxJTJGd2ViJTJGd2Vla19jaG9pY2UuanNvbiUyMiUyQyUyMl9xdWVyeSUyMiUzQSUyMnBhZ2UlM0QwJTI2Y2l0eV9pZCUzRDIzNSUyMiUyQyUyMnByaWNlJTIyJTNBJTIyMjI4JTIyJTJDJTIyaWQlMjIlM0ElMjI1MDI5NzA0JTIyJTJDJTIydGl0bGUlMjIlM0ElMjIlRTYlOUMlQjQlRTclOTQlQjAlRTYlQjMlQjAlRTUlQkMlOEYlRTYlQjUlQjclRTklQjIlOUMlRTclODElQUIlRTklOTQlODUlRUYlQkMlODglRTYlQjMlOUIlRTYlODIlQTYlRTUlOUIlQkQlRTklOTklODUlRTUlQkElOTclRUYlQkMlODklRTUlOEYlOEMlRTQlQkElQkElRTklQTQlOTAlMjIlMkMlMjJ0eXBlJTIyJTNBJTIycHJvZHVjdCUyMiUyQyUyMmVuam95VXJsJTIyJTNBJTIyZW5qb3lhcHAlM0ElMkYlMkZwcm9kdWN0JTJGZGV0YWlsJTNGaWQlM0QxMDE1NTg1JTI2c3ViLXByb2R1Y3QtaWQlM0Q1MDI5NzA0JTIyJTdE",
                "desc":"汤底奶香浓郁 海鲜新鲜到店",
                "enjoy_url":"enjoyapp://product/detail?id=1015585&sub-product-id=5029704",
                "entity_name":"2位",
                "ext":{
                    "product_type":0
                },
                "group":false,
                "id":"5029704",
                "original_price":"¥268",
                "price":"228",
                "tag":"科华北路",
                "title":"朴田泰式海鲜火锅（泛悦国际店）双人餐",
                "type":"product",
                "url":"https://image.ricebook.com/business/17723378223902",
                "url_type":"image"
            },
            {
                "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRnYxJTJGd2ViJTJGd2Vla19jaG9pY2UuanNvbiUyMiUyQyUyMl9xdWVyeSUyMiUzQSUyMnBhZ2UlM0QwJTI2Y2l0eV9pZCUzRDIzNSUyMiUyQyUyMnByaWNlJTIyJTNBJTIyMzE1JTIyJTJDJTIyaWQlMjIlM0ElMjI1MDg4NzQ2JTIyJTJDJTIydGl0bGUlMjIlM0ElMjIlRTUlQjAlOEYlRTYlQjUlQjclRTUlQTAlODIlRTclQjIlQkUlRTglODclQjQlRTUlOEYlOEMlRTQlQkElQkElRTklQTQlOTAlMjIlMkMlMjJ0eXBlJTIyJTNBJTIycHJvZHVjdCUyMiUyQyUyMmVuam95VXJsJTIyJTNBJTIyZW5qb3lhcHAlM0ElMkYlMkZwcm9kdWN0JTJGZGV0YWlsJTNGaWQlM0QxMDM5NzkzJTI2c3ViLXByb2R1Y3QtaWQlM0Q1MDg4NzQ2JTIyJTdE",
                "desc":"色泽金红味美可口的金牌烧鹅",
                "enjoy_url":"enjoyapp://product/detail?id=1039793&sub-product-id=5088746",
                "entity_name":"2位",
                "ext":{
                    "product_type":0
                },
                "group":false,
                "id":"5088746",
                "original_price":"¥332",
                "price":"315",
                "tag":"大慈寺",
                "title":"小海堂精致双人餐",
                "type":"product",
                "url":"https://image.ricebook.com/business/20747225123096",
                "url_type":"image"
            },
            {
                "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRnYxJTJGd2ViJTJGd2Vla19jaG9pY2UuanNvbiUyMiUyQyUyMl9xdWVyeSUyMiUzQSUyMnBhZ2UlM0QwJTI2Y2l0eV9pZCUzRDIzNSUyMiUyQyUyMnByaWNlJTIyJTNBJTIyOTglMjIlMkMlMjJpZCUyMiUzQSUyMjUwODkxOTYlMjIlMkMlMjJ0aXRsZSUyMiUzQSUyMiVFNiU5RSU4MSVFOSVBMyU5RiVFRiVCQyU4OCVFOCVCRiU5QyVFNiVCNCU4QiVFNSVBNCVBQSVFNSU4RiVBNCVFOSU4NyU4QyVFNSVCQSU5NyVFRiVCQyU4OSVFNSVBNCU4RiVFNiU5NyVBNSVFNSU4NSVBOCVFNiU5NiVCMCVFNSU4RiU4QyVFNCVCQSVCQSVFNCVCOCU4QiVFNSU4RCU4OCVFOCU4QyVCNiUyMiUyQyUyMnR5cGUlMjIlM0ElMjJwcm9kdWN0JTIyJTJDJTIyZW5qb3lVcmwlMjIlM0ElMjJlbmpveWFwcCUzQSUyRiUyRnByb2R1Y3QlMkZkZXRhaWwlM0ZpZCUzRDEwNDIyMzElMjZzdWItcHJvZHVjdC1pZCUzRDUwODkxOTYlMjIlN0Q=",
                "desc":"远洋太古里即摘即食的乐活餐厅",
                "enjoy_url":"enjoyapp://product/detail?id=1042231&sub-product-id=5089196",
                "entity_name":"2位",
                "ext":{
                    "product_type":0
                },
                "group":false,
                "id":"5089196",
                "original_price":"¥148",
                "price":"98",
                "tag":"大慈寺",
                "title":"极食（远洋太古里店）夏日全新双人下午茶",
                "type":"product",
                "url":"https://image.ricebook.com/business/21118428723850",
                "url_type":"image"
            },
            {
                "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRnYxJTJGd2ViJTJGd2Vla19jaG9pY2UuanNvbiUyMiUyQyUyMl9xdWVyeSUyMiUzQSUyMnBhZ2UlM0QwJTI2Y2l0eV9pZCUzRDIzNSUyMiUyQyUyMnByaWNlJTIyJTNBJTIyNDklMjIlMkMlMjJpZCUyMiUzQSUyMjUwOTAxMjclMjIlMkMlMjJ0aXRsZSUyMiUzQSUyMiVFNSVCRSVCNyVFNSVCQSVCNyVFNiU4MSU5MiVFNyU4MiVCOSVFNSVCRiU4MyVFOSU5MyVCQSVFNSU4RCU5NSVFNCVCQSVCQSVFOSVBNCU5MCUyMiUyQyUyMnR5cGUlMjIlM0ElMjJwcm9kdWN0JTIyJTJDJTIyZW5qb3lVcmwlMjIlM0ElMjJlbmpveWFwcCUzQSUyRiUyRnByb2R1Y3QlMkZkZXRhaWwlM0ZpZCUzRDEwNDI2MjAlMjZzdWItcHJvZHVjdC1pZCUzRDUwOTAxMjclMjIlN0Q=",
                "desc":"地道粤式好味",
                "enjoy_url":"enjoyapp://product/detail?id=1042620&sub-product-id=5090127",
                "entity_name":"1位",
                "ext":{
                    "product_type":0
                },
                "group":false,
                "id":"5090127",
                "original_price":"¥76",
                "price":"49",
                "tag":"春熙路",
                "title":"德康恒点心铺单人餐",
                "type":"product",
                "url":"https://image.ricebook.com/business/21205913823172",
                "url_type":"image"
            },
            {
                "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRnYxJTJGd2ViJTJGd2Vla19jaG9pY2UuanNvbiUyMiUyQyUyMl9xdWVyeSUyMiUzQSUyMnBhZ2UlM0QwJTI2Y2l0eV9pZCUzRDIzNSUyMiUyQyUyMnByaWNlJTIyJTNBJTIyMjQ4JTIyJTJDJTIyaWQlMjIlM0ElMjI1MDg0Njg4JTIyJTJDJTIydGl0bGUlMjIlM0ElMjIlRTglOEIlOEYlRTUlOUQlQTYlRTQlQjglQUQlRTQlQjglOUMlRTYlOTYlOTklRTclOTAlODYlRUYlQkMlODglRTUlQTQlQUElRTUlOEYlQTQlRTklODclOEMlRTYlOTclOTclRTglODglQjAlRTUlQkElOTclRUYlQkMlODklRTUlODUlQTglRTYlOTYlQjAlRTUlOEYlOEMlRTQlQkElQkElRTklQTQlOTAlMjIlMkMlMjJ0eXBlJTIyJTNBJTIycHJvZHVjdCUyMiUyQyUyMmVuam95VXJsJTIyJTNBJTIyZW5qb3lhcHAlM0ElMkYlMkZwcm9kdWN0JTJGZGV0YWlsJTNGaWQlM0QxMDQwMjcyJTI2c3ViLXByb2R1Y3QtaWQlM0Q1MDg0Njg4JTIyJTdE",
                "desc":"土耳其黎巴嫩摩洛哥等多款中东美食一餐齐享",
                "enjoy_url":"enjoyapp://product/detail?id=1040272&sub-product-id=5084688",
                "entity_name":"2位",
                "ext":{
                    "product_type":0
                },
                "group":false,
                "id":"5084688",
                "original_price":"¥325",
                "price":"248",
                "tag":"大慈寺",
                "title":"苏坦中东料理（太古里旗舰店）全新双人餐",
                "type":"product",
                "url":"https://image.ricebook.com/business/20807934823504",
                "url_type":"image"
            },
            {
                "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRnYxJTJGd2ViJTJGd2Vla19jaG9pY2UuanNvbiUyMiUyQyUyMl9xdWVyeSUyMiUzQSUyMnBhZ2UlM0QwJTI2Y2l0eV9pZCUzRDIzNSUyMiUyQyUyMnByaWNlJTIyJTNBJTIyNzklMjIlMkMlMjJpZCUyMiUzQSUyMjUwOTAwMDYlMjIlMkMlMjJ0aXRsZSUyMiUzQSUyMkVOSk9ZJTIwJUMzJTk3JTIwJUU1JUE0JUE3JUU1JUJFJUI3JUU1JUE0JThGJUU2JTk3JUE1JUU3JUE2JThGJUU4JUEyJThCJTIyJTJDJTIydHlwZSUyMiUzQSUyMnByb2R1Y3QlMjIlMkMlMjJlbmpveVVybCUyMiUzQSUyMmVuam95YXBwJTNBJTJGJTJGcHJvZHVjdCUyRmRldGFpbCUzRmlkJTNEMTA0MjQ1NyUyNnN1Yi1wcm9kdWN0LWlkJTNENTA5MDAwNiUyMiU3RA==",
                "desc":"超值福利 限量发售",
                "enjoy_url":"enjoyapp://product/detail?id=1042457&sub-product-id=5090006",
                "entity_name":"份",
                "ext":{
                    "product_type":1
                },
                "group":false,
                "id":"5090006",
                "price":"79",
                "tag":"春熙路",
                "title":"ENJOY × 大德夏日福袋",
                "type":"product",
                "url":"https://image.ricebook.com/business/21172700623367",
                "url_type":"image"
            },
            {
                "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRnYxJTJGd2ViJTJGd2Vla19jaG9pY2UuanNvbiUyMiUyQyUyMl9xdWVyeSUyMiUzQSUyMnBhZ2UlM0QwJTI2Y2l0eV9pZCUzRDIzNSUyMiUyQyUyMnByaWNlJTIyJTNBJTIyMTQ4JTIyJTJDJTIyaWQlMjIlM0ElMjI1MDM1MTYzJTIyJTJDJTIydGl0bGUlMjIlM0ElMjIlRTUlQjglOEMlRTUlQjAlOTQlRTklQTElQkYlQzIlQjclRTUlQkUlQTElRTclOEUlQkElRTQlQjglQUQlRTklQTQlOTAlRTUlOEUlODUlRTQlQjglQkIlRTUlOEUlQTglRTclODIlQjklRTUlQkYlODMlRTglOEElODIlRTUlOEQlODglRTUlQjglODIlRTclODIlQjklRTUlQkYlODMlRTglODclQUElRTUlOEElQTklMjIlMkMlMjJ0eXBlJTIyJTNBJTIycHJvZHVjdCUyMiUyQyUyMmVuam95VXJsJTIyJTNBJTIyZW5qb3lhcHAlM0ElMkYlMkZwcm9kdWN0JTJGZGV0YWlsJTNGaWQlM0QxMDA5Mzg4JTI2c3ViLXByb2R1Y3QtaWQlM0Q1MDM1MTYzJTIyJTdE",
                "desc":"佛山星级大厨礼备十余新款点心任选 ",
                "enjoy_url":"enjoyapp://product/detail?id=1009388&sub-product-id=5035163",
                "entity_name":"位",
                "ext":{
                    "product_type":0
                },
                "group":false,
                "id":"5035163",
                "original_price":"¥160",
                "price":"148",
                "tag":"高新区",
                "title":"希尔顿·御玺中餐厅主厨点心节午市点心自助",
                "type":"product",
                "url":"https://image.ricebook.com/business/21178875023735",
                "url_type":"image"
            },
            {
                "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRnYxJTJGd2ViJTJGd2Vla19jaG9pY2UuanNvbiUyMiUyQyUyMl9xdWVyeSUyMiUzQSUyMnBhZ2UlM0QwJTI2Y2l0eV9pZCUzRDIzNSUyMiUyQyUyMnByaWNlJTIyJTNBJTIyNDQ4JTIyJTJDJTIyaWQlMjIlM0ElMjI1MDI5NzA2JTIyJTJDJTIydGl0bGUlMjIlM0ElMjIlRTYlOUMlQjQlRTclOTQlQjAlRTYlQjMlQjAlRTUlQkMlOEYlRTYlQjUlQjclRTklQjIlOUMlRTclODElQUIlRTklOTQlODUlRUYlQkMlODglRTYlQjMlOUIlRTYlODIlQTYlRTUlOUIlQkQlRTklOTklODUlRTUlQkElOTclRUYlQkMlODklRTUlOUIlOUIlRTQlQkElQkElRTklQTQlOTAlMjIlMkMlMjJ0eXBlJTIyJTNBJTIycHJvZHVjdCUyMiUyQyUyMmVuam95VXJsJTIyJTNBJTIyZW5qb3lhcHAlM0ElMkYlMkZwcm9kdWN0JTJGZGV0YWlsJTNGaWQlM0QxMDE1NTg0JTI2c3ViLXByb2R1Y3QtaWQlM0Q1MDI5NzA2JTIyJTdE",
                "desc":"金丝设计的独栋复式洋楼",
                "enjoy_url":"enjoyapp://product/detail?id=1015584&sub-product-id=5029706",
                "entity_name":"4位",
                "ext":{
                    "product_type":0
                },
                "group":false,
                "id":"5029706",
                "original_price":"¥524",
                "price":"448",
                "tag":"科华北路",
                "title":"朴田泰式海鲜火锅（泛悦国际店）四人餐",
                "type":"product",
                "url":"https://image.ricebook.com/business/17764972413612",
                "url_type":"image"
            }
        ]
    }

			axios.post('/api/getcitydata',pro)
						.then(function(res){
							console.log(res)
						})


			},
            getFindCarousel(){

                var pro = {
                    img:'https://image.ricebook.com/business/23175261623972?imageView2/2/w/670' ,
                    text1:"超级星期五",
                    text2:'满450减45元 满180减15元！春天里，约会你',
                    text3:'一览蓉城春景的星级酒店、浪漫满分的精致西餐厅......白色情人节特辑'
                }
                axios.post('/api/getfindcarousel',pro)
                        .then(function(res){
                            console.log(res)
                        })
            },
            savedetails(){
                var pro = {
    "modules":[
        {
            "compatibility_policy":{
                "alert_message":"当前应用版本太低",
                "policy":"alert"
            },
            "data":{
                "restaurants":[
                    {
                        "area_id":2379,
                        "area_name":"科华北路",
                        "city_id":0,
                        "enjoy_url":"enjoyapp://restaurant/profile?id=11669424",
                        "latitude":30.61199951171875,
                        "license":{
                            "enjoy_url":"https://topic.ricebook.com/topicpage/product_licence.html?restaurant_id=11669424",
                            "icon":"https://image.ricebook.com/business/18915887513738",
                            "text":"营业许可资质"
                        },
                        "longitude":104.08351135253906,
                        "price_number":0,
                        "restaurant_address":"武侯区长荣路56号1栋5号楼",
                        "restaurant_id":11669424,
                        "restaurant_image":[
                            {
                                "img_url":"https://image.ricebook.com/business/18137675013766",
                                "special_show":false
                            },
                            {
                                "img_url":"https://image.ricebook.com/business/18137675013058",
                                "special_show":false
                            },
                            {
                                "img_url":"https://image.ricebook.com/business/18137675013380",
                                "special_show":false
                            }
                        ],
                        "restaurant_name":"朴田海鲜火锅（泛悦国际店）",
                        "restaurant_phone_numbers":[
                            "028-69868710"
                        ],
                        "state":0
                    }
                ]
            },
            "id":5,
            "index":1
        },
        {
            "compatibility_policy":{
                "alert_message":"当前应用版本太低",
                "policy":"ignore"
            },
            "data":{
                "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRmluZm8lMkZwcm9kdWN0X2RldGFpbC5qc29uJTIyJTJDJTIyX3F1ZXJ5JTIyJTNBJTIyc3ViX3Byb2R1Y3RfaWQlM0Q1MDI5NzA0JTI2cHJvZHVjdF9pZCUzRDEwMTU1ODUlMjIlMkMlMjJzdWJQcm9kdWN0SWQlMjIlM0E1MDI5NzA1JTJDJTIyc291cmNlJTIyJTNBJTIycHJvZHVjdCUyMiUyQyUyMnRleHQlMjIlM0ElMjIlRTUlQkUlODglRTYlQTMlOTIlRTUlOTYlOTQlRUYlQkMlOEMlRTYlQUYlOEYlRTYlQUMlQTElRTklODMlQkQlRTglQjYlODUlRTclQjQlOUElRTYlODQlOUIlRTUlOTAlODMlRTQlQkIlOTYlRTUlQUUlQjYlRTclOUElODQlRTYlQjUlQjclRTklQUUlQUUlRUYlQkMlOEMlRTclODklQjklRTUlODglQTUlRTYlOTYlQjAlRTklQUUlQUUlRUYlQkMlODElRTUlQjAlQjElRTYlOTglQUYlRTYlOEUlOTIlRTQlQkQlOEQlRTYlOUMlODklRTklQkIlOUUlRTglOTElOTclRTYlODAlQTUlRUYlQkMlODElMjIlMkMlMjJpZCUyMiUzQTE1MDUxNDQ2MjE0MDAwMDIlMkMlMjJyZXN0YXVyYW50SWQlMjIlM0ExMTY2OTQyNCUyQyUyMmVuam95VXJsJTIyJTNBJTIyZW5qb3lhcHAlM0ElMkYlMkZwcm9kdWN0JTJGZmVlZGJhY2slMkZsaXN0JTNGcHJvZHVjdF9pZCUzRDEwMTU1ODUlMjIlN0Q=",
                "avatar":"https://image.ricebook.com/business/22268467623067",
                "create_time":1505144621000,
                "enjoy_url":"enjoyapp://product/feedback/list?product_id=1015585",
                "id":1505144621400002,
                "images":[
                    "https://image.ricebook.com/feedback/1505144620340001",
                    "https://image.ricebook.com/feedback/1505144620340005",
                    "https://image.ricebook.com/feedback/1505144620340003",
                    "https://image.ricebook.com/feedback/1505144620340002",
                    "https://image.ricebook.com/feedback/1505144620340004",
                    "https://image.ricebook.com/feedback/1505144620340007"
                ],
                "merchant_id":5211,
                "nick_name":"ENJOY_66ip9xGG",
                "order_id":1503709665320001,
                "restaurant_id":11669424,
                "scores":[
                    {
                        "id":3,
                        "name":"菜品质量",
                        "score":5
                    },
                    {
                        "id":4,
                        "name":"就餐环境",
                        "score":5
                    },
                    {
                        "id":5,
                        "name":"餐厅服务",
                        "score":5
                    }
                ],
                "source":"product",
                "sub_product_id":5029705,
                "tags":[

                ],
                "text":"很棒喔，每次都超級愛吃他家的海鮮，特別新鮮！就是排位有點著急！",
                "update_time":1510418225000,
                "user_id":21487351124578
            },
            "id":16,
            "index":2
        },
        {
            "compatibility_policy":{
                "alert_message":"当前应用版本太低",
                "policy":"alert"
            },
            "data":{
                "contents":[
                    {
                        "sub_title":"海鲜套餐",
                        "text":[
                            "虾/大目鱼/肥牛/鱼丸/生菜 ",
                            "豆腐/南极笋/秋葵/金针菇/雪皮菜 ",
                            "虾滑/蟹/排骨/肉滑/午餐肉 ",
                            "巴沙鱼/花螺/ 娃娃菜/玉米",
                            "魔芋丝/土豆/藕/番茄",
                            " "
                        ]
                    },
                    {
                        "sub_title":"蘸碟",
                        "text":[
                            "（6选2）",
                            "朴田秘制蘸碟",
                            "鲜香泰式蘸碟",
                            "泰式蘸碟",
                            "香辣干碟",
                            "小米辣蘸碟",
                            "芥末蘸碟"
                        ]
                    },
                    {
                        "sub_title":"特色",
                        "text":[
                            "烤扇贝2只",
                            " "
                        ]
                    },
                    {
                        "sub_title":"饮品",
                        "text":[
                            "（3选2）",
                            "原味莫吉托",
                            "百柚苏打",
                            "西柚C多多"
                        ]
                    },
                    {
                        "sub_title":"提示",
                        "text":[
                            "套餐包含锅底",
                            "因季节变化 海鲜类食材采购情况不同",
                            "部分菜品将等价替换",
                            "请以实际到店为准"
                        ]
                    }
                ]
            },
            "id":6,
            "index":3
        },
        {
            "compatibility_policy":{
                "alert_message":"当前应用版本太低",
                "policy":"alert"
            },
            "data":{
                "lights":[
                    {
                        "content":"PAKTIN*plus 为朴田泰式海鲜火锅的升级版餐厅，独栋复式洋楼，坐落于长荣路，餐厅一改丝竹路的田园小清新风格，金丝设计的外观，呈现出富丽堂皇的气派。复式洋楼囊括一楼的咖啡厅，二楼三楼的泰式海鲜火锅，从午餐到夜场皆可在此享受。此次与 ENJOY 合作推出泰式海鲜火锅双人餐。",
                        "img_url":"https://image.ricebook.com/business/18137680613767",
                        "title":"囊括咖啡厅海鲜锅 金丝设计的独栋复式洋楼"
                    },
                    {
                        "content":"冬荫功汤是一道泰国名汤，也是“世界十大名汤”之一。在泰语中，“冬荫”指酸辣，“功”即是虾，合起来就是酸辣虾汤。泰式海鲜火锅，终其根本在于泰式冬荫功汤底。PAKTIN*plus 跳出泰国元素，将传统冬荫功的酸辣重口味弱化，浓浓奶香味更受本地食客们的欢迎。海鲜经过精心挑选，基围虾上桌时甚至还在动，足见新鲜。",
                        "img_url":"https://image.ricebook.com/business/17723397413910",
                        "title":"将泰式风味结合四川人口味改良 冬阴功汤底奶香更足"
                    },
                    {
                        "content":"PAKTIN*plus 不仅汤底香，小到蘸碟也下足功夫。因为老板认为，长着一张“香香嘴”的四川人在吃火锅时，也十分看重蘸碟的味道。Paktin*plus 不光有鲜辣的「泰式蘸碟」、尖辣的「小米辣蘸碟」；也有独家秘制闻一闻就香辣入味的「朴田秘制蘸碟」，更创新了不辣的「鲜香泰式蘸碟」，还有专为特殊口味定制的「芥末蘸碟」与「香辣干碟」。",
                        "img_url":"https://image.ricebook.com/business/18137689413384",
                        "title":"吃火锅就要尝蘸碟 「秘制蘸碟」香辣提味"
                    }
                ],
                "text_array":[
                    "囊括咖啡厅海鲜锅 金丝设计的独栋复式洋楼",
                    "将泰式风味结合四川人口味改良 冬阴功汤底奶香更足",
                    "吃火锅就要尝蘸碟 「秘制蘸碟」香辣提味"
                ]
            },
            "id":4,
            "index":4
        },
        {
            "compatibility_policy":{
                "alert_message":"当前应用版本太低",
                "policy":"alert"
            },
            "data":{
                "contents":[
                    {
                        "text":"使用日期：2016.8.4-2017.9.30；"
                    },
                    {
                        "text":"使用时段：11:00-22:00；"
                    },
                    {
                        "text":"高峰期可能排队，建议错开高峰期到店用餐；"
                    },
                    {
                        "text":"本产品支持随时退款；"
                    },
                    {
                        "text":"此礼遇不与店内其他优惠同享；"
                    },
                    {
                        "text":"如需开具发票，请具体咨询商户；"
                    },
                    {
                        "text":"如有疑问，请联系 ENJOY 客服。电话：4008-909-511；微信：enjoyricebook"
                    }
                ],
                "express":[

                ],
                "restaurant_phone_number":[
                    "028-69868710"
                ]
            },
            "id":9,
            "index":5
        },
        {
            "compatibility_policy":{
                "alert_message":"当前应用版本太低",
                "policy":"alert"
            },
            "data":{
                "recommend":[
                    {
                        "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRmluZm8lMkZwcm9kdWN0X2RldGFpbC5qc29uJTIyJTJDJTIyX3F1ZXJ5JTIyJTNBJTIyc3ViX3Byb2R1Y3RfaWQlM0Q1MDI5NzA0JTI2cHJvZHVjdF9pZCUzRDEwMTU1ODUlMjIlMkMlMjJfZnJvbSUyMiUzQSUyMnJlY29tbWVuZCUyMiUyQyUyMnByb2R1Y3RJZCUyMiUzQTEwMTcwMzYlMkMlMjJfaW5kZXglMjIlM0EwJTdE",
                        "area_name":"青羊区",
                        "desc":"20年经验香港名厨创意之作",
                        "distance":0,
                        "enjoy_url":"enjoyapp://product/detail?id=1017036",
                        "ext":{
                            "product_type":0,
                            "display_prop":[

                            ],
                            "light_spot":[
                                {
                                    "img":"18276369223940",
                                    "img_url":"https://image.ricebook.com/business/18276369223940",
                                    "title":"集时尚与美学生活于一体的素食生活馆",
                                    "type":1,
                                    "content":"Meli&Moli 联合众多国内外独立式设计品牌，打造集珠宝、服装、美学生活、书吧、素食等多元素为一体的生活馆。岁月静好花香阵阵，空气中飘着丝丝精油的芬芳，给生活带来品质的追求和艺术的感染力，喝杯咖啡，看看书，顺便穿走一条心仪已久的裙子，对生活品质有要求的女性心中那一个理想的都市后花园。"
                                },
                                {
                                    "img":"18276372223588",
                                    "img_url":"https://image.ricebook.com/business/18276372223588",
                                    "title":"20年经验香港名厨温柔善待好食材",
                                    "type":1,
                                    "content":"餐厅主厨许嘉恒，醉心美食20年，曾师从香港十大名厨，并成为当时香港餐饮协会年轻的港籍会员。崇尚使用优质食材，并且坚持任何搭配都存在无限可能性，不存在好坏之分，只有美味与否。许主厨善于通过美食来沟通人与食物，与自然，以及人与人之间的情感，唤醒内心深处对生活热爱的那份情怀。"
                                },
                                {
                                    "img":"18276375013298",
                                    "img_url":"https://image.ricebook.com/business/18276375013298",
                                    "title":"秘制披萨脆软浓香 健康素食也能甘鲜可口",
                                    "type":1,
                                    "content":"全采用进口食材，通过不断的尝试与精心搭配，烤制出别具匠心的「芝士牛油果披萨」浓香动人不输肉食之美；「芝士榴莲披萨」含有丰富的留恋肉甜香软嫩；「土豆蘑菇披萨」马铃薯甘甜淳朴的香气中增添了蘑菇的嫩脆；除此之外还有劲道弹牙的意面搭配煨煮多时浓郁醇厚的多种秘制酱料，令无负担的素食也变得喷香诱人无法抵抗。"
                                }
                            ]
                        },
                        "origin_price":8800,
                        "price":4800,
                        "product_id":1017036,
                        "product_image_url":"https://image.ricebook.com/business/18276363723938",
                        "product_name":"Meli&Moli 生活馆单人轻食",
                        "sell_state":1,
                        "show_entity_name":"位"
                    },
                    {
                        "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRmluZm8lMkZwcm9kdWN0X2RldGFpbC5qc29uJTIyJTJDJTIyX3F1ZXJ5JTIyJTNBJTIyc3ViX3Byb2R1Y3RfaWQlM0Q1MDI5NzA0JTI2cHJvZHVjdF9pZCUzRDEwMTU1ODUlMjIlMkMlMjJfZnJvbSUyMiUzQSUyMnJlY29tbWVuZCUyMiUyQyUyMnByb2R1Y3RJZCUyMiUzQTEwMzM3NzglMkMlMjJfaW5kZXglMjIlM0ExJTdE",
                        "area_name":"金牛区",
                        "desc":"诚意满满吃到饱腹的精致日料",
                        "distance":0,
                        "enjoy_url":"enjoyapp://product/detail?id=1033778",
                        "ext":{
                            "product_type":0,
                            "display_prop":[

                            ],
                            "light_spot":[
                                {
                                    "img":"19183736113897",
                                    "img_url":"https://image.ricebook.com/business/19183736113897",
                                    "title":"在烂漫的樱花树下品地道日料",
                                    "type":1,
                                    "content":"上野樱花的装饰风格以樱花为主题的日料店。走进店内，随处可见粉色的浪漫樱花，仿佛真的置身日本的上野车站。占了整面墙的樱花壁纸和仿真的樱花树使得整家店充满了生机。店内以原木色为主色调，实木地板使空间显得更加温暖。简单的木制线条隔断很好地为食客们区分出私人的空间，使得就餐的环境舒适惬意。头顶上的古色古香的灯饰充满和风情调。顶面的吊柜和充满设计感的线条切割又增添了几分巧思和精致。"
                                },
                                {
                                    "img":"19183738623613",
                                    "img_url":"https://image.ricebook.com/business/19183738623613",
                                    "title":"诚意满满的礼遇好食又饱腹",
                                    "type":1,
                                    "content":"日料通常大都精致小巧，食客们可能有时会吃不饱，而此次礼遇中包涵了刺身寿司炸物，主食沙拉和汤品。以诚意满满的优惠价格，在保持日料精致的特色下让食客们完全饱腹。甄选新鲜的三文鱼制作的「三文鱼刺身」鲜嫩肥美，厚切口感扎实，薄切口感爽滑。创意的「鹅肝寿司」入口即化，经过烤制以后恰好去除了腥味，而且肥而不腻，创意的搭配巧妙新奇。上野的特色拉面，原汤醇香浓郁，拉面劲道爽口，饱满的一大碗，让食客们大快朵颐，暖心又暖胃。"
                                }
                            ]
                        },
                        "origin_price":18200,
                        "price":14900,
                        "product_id":1033778,
                        "product_image_url":"https://image.ricebook.com/business/19183684323134",
                        "product_name":"上野樱花日式精致料理（蜀汉路店）双人餐",
                        "sell_state":1,
                        "show_entity_name":"2位"
                    },
                    {
                        "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRmluZm8lMkZwcm9kdWN0X2RldGFpbC5qc29uJTIyJTJDJTIyX3F1ZXJ5JTIyJTNBJTIyc3ViX3Byb2R1Y3RfaWQlM0Q1MDI5NzA0JTI2cHJvZHVjdF9pZCUzRDEwMTU1ODUlMjIlMkMlMjJfZnJvbSUyMiUzQSUyMnJlY29tbWVuZCUyMiUyQyUyMnByb2R1Y3RJZCUyMiUzQTEwMzUzNzIlMkMlMjJfaW5kZXglMjIlM0EyJTdE",
                        "area_name":"桐梓林",
                        "desc":"独立榻榻米包间的东瀛烤肉小铺 ",
                        "distance":0,
                        "enjoy_url":"enjoyapp://product/detail?id=1035372",
                        "ext":{
                            "product_type":0,
                            "display_prop":[

                            ],
                            "light_spot":[
                                {
                                    "img":"20202829523380",
                                    "img_url":"https://image.ricebook.com/business/20202829523380",
                                    "title":"酸甜合宜的幼滑鹅肝寿司",
                                    "type":1,
                                    "content":"赤坂惠的寿司均选用日本进口寿司米制作，「火炙鹅肝寿司卷」将肥美丝滑的鹅肝与软糯的寿司做配。加入特制的寿司醋，酸甜适中，更能激发鹅肝原本的鲜香，并起到解腻的效用，让人回味无穷。"
                                },
                                {
                                    "img":"20202830923377",
                                    "img_url":"https://image.ricebook.com/business/20202830923377",
                                    "title":"传统和风的东瀛烤肉小铺",
                                    "type":1,
                                    "content":"赤坂惠每处细节充满充满东瀛特色，不同规格的日式榻榻米包间满足了多种就餐情景的需求，不论两人约会、朋友小聚或是商务宴请等都能找到合适的位置。店员们也都身着日本传统服饰，店内墙壁上布置了诸多日式风格装饰画，让前来的食客能于独立包间内私密惬意享受浓郁日本风情。"
                                }
                            ]
                        },
                        "origin_price":32800,
                        "price":24800,
                        "product_id":1035372,
                        "product_image_url":"https://image.ricebook.com/business/20202771323380",
                        "product_name":"赤坂惠日式料理双人餐",
                        "sell_state":1,
                        "show_entity_name":"2位"
                    },
                    {
                        "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRmluZm8lMkZwcm9kdWN0X2RldGFpbC5qc29uJTIyJTJDJTIyX3F1ZXJ5JTIyJTNBJTIyc3ViX3Byb2R1Y3RfaWQlM0Q1MDI5NzA0JTI2cHJvZHVjdF9pZCUzRDEwMTU1ODUlMjIlMkMlMjJfZnJvbSUyMiUzQSUyMnJlY29tbWVuZCUyMiUyQyUyMnByb2R1Y3RJZCUyMiUzQTEwNDU4MDklMkMlMjJfaW5kZXglMjIlM0EzJTdE",
                        "area_name":"武侯区",
                        "desc":"畅享海鲜 超值福利",
                        "distance":0,
                        "enjoy_url":"enjoyapp://product/detail?id=1045809",
                        "ext":{
                            "product_type":0,
                            "display_prop":[

                            ],
                            "light_spot":[
                                {
                                    "img":"21723242523912",
                                    "img_url":"https://image.ricebook.com/business/21723242523912",
                                    "title":"闹市中的静谧桃源 ",
                                    "type":1,
                                    "content":"成都明宇尚雅饭店隐蔽于市中心的静谧桃源，依偎在锦江河畔，静享绝美风光中的超然舒适生活。兰图咖啡厅重新装修并更名为全日餐吧，将于2017年9月29日开业。餐厅新开数十个档口，拥有上百种丰富的菜品。以西式美食以及生猛海鲜为主，味道鲜美，种类丰富。同时为食客奉上极具四川特色的小吃和地道的中式菜肴。大落地窗静享绝美的城市风光，简单而不简约的时尚设计，呈现舒适优雅的用餐气氛，是家庭聚会，朋友聚会和个人食客的极好选择。全日餐吧有着宽敞的宽敞的半开放式厨房，可供食客欣赏厨艺高超的主厨如何通过料理让食材变化成美味。"
                                },
                                {
                                    "img":"21723244123913",
                                    "img_url":"https://image.ricebook.com/business/21723244123913",
                                    "title":"肥美多汁的野生蚝王 哈根达斯冰淇淋无限畅享",
                                    "type":1,
                                    "content":"全日餐吧提供琳琅满目的海味生鲜，包括蟹脚、红虾、青口、三点蟹、翡翠螺等，更有无限量肥美多汁的生蚝。作为主持推荐的波士顿龙虾，肉质细嫩滑脆，微微焦香的芝士融化裹挟于紧致的虾肉，鲜香醇厚的滋味，让海鲜爱好者大呼过瘾。多款经典美味的中式菜，更是结合了成都特色，为食客献上火红辣口味以及藤椒麻酥口味的钵钵鸡，更有成都名小吃的担担面等一饱口福。香草、巧克力、芒果等不同口味的哈根达斯冰淇淋无限畅享，每一口都让舌尖充满甜蜜。"
                                }
                            ]
                        },
                        "origin_price":23800,
                        "price":15800,
                        "product_id":1045809,
                        "product_image_url":"https://image.ricebook.com/business/21790732823367",
                        "product_name":"明宇尚雅酒店·全日餐吧海鲜自助晚宴",
                        "sell_state":1,
                        "show_entity_name":"位"
                    },
                    {
                        "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRmluZm8lMkZwcm9kdWN0X2RldGFpbC5qc29uJTIyJTJDJTIyX3F1ZXJ5JTIyJTNBJTIyc3ViX3Byb2R1Y3RfaWQlM0Q1MDI5NzA0JTI2cHJvZHVjdF9pZCUzRDEwMTU1ODUlMjIlMkMlMjJfZnJvbSUyMiUzQSUyMnJlY29tbWVuZCUyMiUyQyUyMnByb2R1Y3RJZCUyMiUzQTEwMDcwMTUlMkMlMjJfaW5kZXglMjIlM0E0JTdE",
                        "area_name":"锦江区",
                        "desc":"ENJOY 独享赠送鲍汁自制豆腐",
                        "distance":0,
                        "enjoy_url":"enjoyapp://product/detail?id=1007015",
                        "ext":{
                            "product_type":0,
                            "display_prop":[

                            ],
                            "light_spot":[
                                {
                                    "img":"17136761913187",
                                    "img_url":"https://image.ricebook.com/business/17136761913187",
                                    "title":"从2000多年古蜀文明汲取灵感 画卷式长廊呈现东方韵味",
                                    "type":1,
                                    "content":"位于成都富力丽思卡尔顿酒店26层的丽轩中餐厅，设计灵感来自2000多年的古蜀文明，以“芙蓉古都”和“丝绸之路”为灵感，随处可见的蜀锦装饰、缤纷的花朵，给摩登时尚的餐厅点缀出成都气息。画卷式长廊，将旧时繁荣盛景呈现眼前。十一间尊贵包间，以花朵为灵感源泉，让宾客在私密氛围中细品东方韵味。"
                                },
                                {
                                    "img":"17136764213869",
                                    "img_url":"https://image.ricebook.com/business/17136764213869",
                                    "title":"星级酒店行政主厨亲自设计菜单 精选多款招牌点心",
                                    "type":1,
                                    "content":"丽思卡尔顿新上任中厨行政主厨李师傅来自四川宜宾，精通粤菜与川菜，拥有超过二十二年烹饪经验。曾在多家国际品牌酒店任职，足迹遍布四川、北京、苏州及东非乌干达、土耳其伊斯坦布尔。"
                                },
                                {
                                    "img":"17136766613703",
                                    "img_url":"https://image.ricebook.com/business/17136766613703",
                                    "title":"品味正宗川粤风味 零点无限量现做现尝",
                                    "type":1,
                                    "content":"本次菜单分为“滋味前菜”“厨品小菜”“蒸彩纷呈”“亲蜜无间”等四大系列，包括广式烧味、蒸点、甜品等不胜枚举的地道粤点。「蜜汁叉烧肠粉」采用地道广式叉烧做法，淋上蜜汁，肉的香嫩和蜜汁的清甜很好地混合，口感香浓。还有备受食客喜爱的「松露笋尖虾饺皇」、「瑶柱干蒸烧卖」、「银萝千层酥」、「蜜汁叉烧酥」、「黑松露菩提素果」等特色点心。除粤菜外，为迎合四川人的口感，主厨也特意准备一系列四川菜式，诸如「鲜辣脆鱼皮」，「干葱辣子鸡」、「水煮牛肉」、「酸菜鱼」等特色川菜，让食客享受一顿丰盛饱食。"
                                }
                            ]
                        },
                        "origin_price":38900,
                        "price":26800,
                        "product_id":1007015,
                        "product_image_url":"https://image.ricebook.com/business/17136724413865",
                        "product_name":"丽思卡尔顿·丽轩中餐厅点心自助晚餐",
                        "sell_state":1,
                        "show_entity_name":"位"
                    },
                    {
                        "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRmluZm8lMkZwcm9kdWN0X2RldGFpbC5qc29uJTIyJTJDJTIyX3F1ZXJ5JTIyJTNBJTIyc3ViX3Byb2R1Y3RfaWQlM0Q1MDI5NzA0JTI2cHJvZHVjdF9pZCUzRDEwMTU1ODUlMjIlMkMlMjJfZnJvbSUyMiUzQSUyMnJlY29tbWVuZCUyMiUyQyUyMnByb2R1Y3RJZCUyMiUzQTEwMzUzMDYlMkMlMjJfaW5kZXglMjIlM0E1JTdE",
                        "desc":"成立于伦敦的独立品牌",
                        "distance":0,
                        "enjoy_url":"enjoyapp://product/detail?id=1035306",
                        "ext":{
                            "product_type":1,
                            "display_prop":[
                                {
                                    "background_color":"#f6f6f6",
                                    "name":"品牌直邮",
                                    "background_img_color":"red",
                                    "font_color":"#1a1a1a"
                                },
                                {
                                    "background_color":"#f6f6f6",
                                    "name":"可包邮",
                                    "background_img_color":"red",
                                    "font_color":"#1a1a1a"
                                }
                            ],
                            "light_spot":[
                                {
                                    "img":"20211107523078",
                                    "img_url":"https://image.ricebook.com/business/20211107523078",
                                    "title":"以精选面料和创新工艺备受都市女性推崇",
                                    "type":1,
                                    "content":"Not Just Pajama 是成立于伦敦的独立品牌，产品分为家居、度假服饰（Pajama & Resort）、睡眠用品（Beauty Sleeper）和旅行用品（Travel Collection）三个主系列，以打破传统的外穿式睡衣（Walking Sleepwear）而备受都市女性推崇。Not Just Pajama 密切关注客户的舒适体验以及紧趋时尚潮流，无论是男女家居睡衣、睡袍或度假服饰，每件都融入了他们自己对设计的理解，为产品赋予了现代随意的时尚感。Not Just Pajama 希望以精选面料和创新的混搭工艺，让每位穿戴者都能体验到舒适质感的居家生活。"
                                },
                                {
                                    "img":"20211143323077",
                                    "img_url":"https://image.ricebook.com/business/20211143323077",
                                    "title":"柔软面料内填充有法国进口天然薰衣草籽",
                                    "type":1,
                                    "content":"英国 Not Just Pajama 收纳袋小号，少女粉、薄荷绿、婴儿蓝、绅士蓝四色可供选择。面料和填充物选用化纤材质，手感顺滑柔软。收纳袋内还填充有法国进口的天然薰衣草籽，具有除味增添芳香的作用。此系列小号收纳袋，适合收纳眼罩、手绢、小手巾等；因为尺寸适中，平时随身放入包内作为小物品的收纳袋也十分合适。"
                                }
                            ]
                        },
                        "price":4900,
                        "product_id":1035306,
                        "product_image_url":"https://image.ricebook.com/business/20211100523072",
                        "product_name":"英国 Not Just Pajama 收纳袋小号",
                        "sell_state":1,
                        "show_entity_name":"件"
                    },
                    {
                        "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRmluZm8lMkZwcm9kdWN0X2RldGFpbC5qc29uJTIyJTJDJTIyX3F1ZXJ5JTIyJTNBJTIyc3ViX3Byb2R1Y3RfaWQlM0Q1MDI5NzA0JTI2cHJvZHVjdF9pZCUzRDEwMTU1ODUlMjIlMkMlMjJfZnJvbSUyMiUzQSUyMnJlY29tbWVuZCUyMiUyQyUyMnByb2R1Y3RJZCUyMiUzQTEwMzYwMTklMkMlMjJfaW5kZXglMjIlM0E2JTdE",
                        "area_name":"盐市口",
                        "desc":"老牌星级酒店尽尝十四款经典成都味道",
                        "distance":0,
                        "enjoy_url":"enjoyapp://product/detail?id=1036019",
                        "ext":{
                            "product_type":0,
                            "display_prop":[
                                {
                                    "background_color":"#f6f6f6",
                                    "name":"地铁沿线",
                                    "background_img_color":"red",
                                    "font_color":"#1a1a1a"
                                }
                            ],
                            "light_spot":[
                                {
                                    "img":"20282404723537",
                                    "img_url":"https://image.ricebook.com/business/20282404723537",
                                    "title":"十四款经典成都小吃任选 体验地道老成都滋味",
                                    "type":1,
                                    "content":"此次礼遇中包含了十四款成都经典传统小吃可选，叶儿耙、担担面、钟水饺、蛋烘糕，每款都是老成都的代表滋味，主厨以精湛的厨艺烹饪地道川式美味，还原成都小吃精髓。「钟水饺」为代表的地道成都小吃以主厨特酿的辣油为料，红亮润泽，让人食欲大开。「叶儿耙」用糯米碾成面粉，包裹上肥瘦兼半的内陷儿，垫上叶儿，上锅蒸熟，咬一口，热汤便从齿间流出，软香粘糯。每一筷子都让食客流连于成都小吃的诱人滋味，难以自拔。"
                                },
                                {
                                    "img":"20282405623487",
                                    "img_url":"https://image.ricebook.com/business/20282405623487",
                                    "title":"师从中国烹饪名师卢朝华的李兵主厨",
                                    "type":1,
                                    "content":"岷轩中餐厅的主厨李兵先生是中国烹饪名师，师从中国烹饪大师卢朝华门下，从事烹饪工作25年有余。90年就进入五星级酒店系统学习烹饪专业基础知识。02年至今，管理多家酒店厨政工作。一直秉承坚持、传承、创新、融合理念。正如他说，没有传统作为基石，就没有创新。"
                                },
                                {
                                    "img":"20282413623538",
                                    "img_url":"https://image.ricebook.com/business/20282413623538",
                                    "title":"繁华市中心酒店的临江美景",
                                    "type":1,
                                    "content":"岷轩中餐厅位于成都历史悠久的知名酒店——岷山饭店2楼，临窗便是成都标志性的锦江。餐厅装潢大气典雅却不失温馨恬静，在闲暇的晌午，与好友闲坐窗前，享受着酒店式悉心服务的同时，也能舒心享用大厨精心制作的地道成都美食。"
                                }
                            ]
                        },
                        "origin_price":11200,
                        "price":9800,
                        "product_id":1036019,
                        "product_image_url":"https://image.ricebook.com/business/20282360123536",
                        "product_name":"岷山饭店·珉轩中餐厅单人午餐",
                        "sell_state":1,
                        "show_entity_name":"位"
                    },
                    {
                        "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRmluZm8lMkZwcm9kdWN0X2RldGFpbC5qc29uJTIyJTJDJTIyX3F1ZXJ5JTIyJTNBJTIyc3ViX3Byb2R1Y3RfaWQlM0Q1MDI5NzA0JTI2cHJvZHVjdF9pZCUzRDEwMTU1ODUlMjIlMkMlMjJfZnJvbSUyMiUzQSUyMnJlY29tbWVuZCUyMiUyQyUyMnByb2R1Y3RJZCUyMiUzQTEwMzgxNTAlMkMlMjJfaW5kZXglMjIlM0E3JTdE",
                        "area_name":"盐市口",
                        "desc":"市中心老牌五星酒店尽揽府河美景",
                        "distance":0,
                        "enjoy_url":"enjoyapp://product/detail?id=1038150",
                        "ext":{
                            "product_type":0,
                            "display_prop":[
                                {
                                    "background_color":"#f6f6f6",
                                    "name":"城中招牌店",
                                    "background_img_color":"red",
                                    "font_color":"#1a1a1a"
                                },
                                {
                                    "background_color":"#f6f6f6",
                                    "name":"地铁沿线",
                                    "background_img_color":"red",
                                    "font_color":"#1a1a1a"
                                },
                                {
                                    "background_color":"#f6f6f6",
                                    "name":"高空美景",
                                    "background_img_color":"red",
                                    "font_color":"#1a1a1a"
                                }
                            ],
                            "light_spot":[
                                {
                                    "img":"20558907423091",
                                    "img_url":"https://image.ricebook.com/business/20558907423091",
                                    "title":"繁华市中心酒店纵览高空美景",
                                    "type":1,
                                    "content":"The River House 西餐厅位于成都历史悠久的知名酒店——岷山饭店顶层21楼，从明亮的全景落地窗向下俯瞰，就是成都标志性的府南河。餐厅装潢大气典雅却不失温馨恬静，在闲暇的午后，与一两好友闲坐窗前，享受着酒店式悉心服务的同时，也在悠扬的古典音乐里放松小憩。"
                                },
                                {
                                    "img":"20558911923111",
                                    "img_url":"https://image.ricebook.com/business/20558911923111",
                                    "title":"以新鲜蛋黄做酱烘托芦笋迷人清香",
                                    "type":1,
                                    "content":"The River House 别具匠心的「芦笋沙拉」把面粉、鸡蛋与水和成浆，并将流心新鲜鸡蛋裹浆放入油锅炸成金黄色，酥脆表皮裂开同时鲜香蛋黄流出，鲜美蛋香混合芦笋独有的清新香味，搭配有世界三大珍味之一盛誉的黑松露与色泽嫩红帕尔马火腿，黑松露独特的森林泥土气息与柔软丝滑的喷香火腿在唇齿间碰撞。"
                                },
                                {
                                    "img":"20558915823113",
                                    "img_url":"https://image.ricebook.com/business/20558915823113",
                                    "title":"真空低温烹调软糯细腻的喷香牛小排",
                                    "type":1,
                                    "content":"餐厅主厨 Robert 为人亲切、谦和，作为80后年轻一代，已有十年厨房工作经验。热爱烹饪的他，对待食物充满热情与创造力。The River House 每进一批上好食材， Robert 都会“因材施教”，创作出最适合食物本身的佳肴。此次推出的主菜「低温煮黑胡椒澳洲牛小排」特选澳洲进口牛小排，并将牛小排用抽真空的办法包装，以65度左右的低温恒温水浴慢煮数小时，将牛肉充分胶质软化，最终呈现肉质软糯细腻的上佳口感。肉块入口时能清楚感受到汁水随着牙齿的咀嚼而散溢开来，牛肉的香味很好地传递到舒展口腔的每一个味蕾，配合意大利芹、番茄、红胡椒、百里香等配料佐味，混合滋味在唇齿间盘旋游走，让食客纵情沉浸于大口吃肉的美好时光里。"
                                }
                            ]
                        },
                        "origin_price":42800,
                        "price":19800,
                        "product_id":1038150,
                        "product_image_url":"https://image.ricebook.com/business/20558895723115",
                        "product_name":"岷山饭店·The River House 西餐厅单人午餐",
                        "sell_state":1,
                        "show_entity_name":"位"
                    },
                    {
                        "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRmluZm8lMkZwcm9kdWN0X2RldGFpbC5qc29uJTIyJTJDJTIyX3F1ZXJ5JTIyJTNBJTIyc3ViX3Byb2R1Y3RfaWQlM0Q1MDI5NzA0JTI2cHJvZHVjdF9pZCUzRDEwMTU1ODUlMjIlMkMlMjJfZnJvbSUyMiUzQSUyMnJlY29tbWVuZCUyMiUyQyUyMnByb2R1Y3RJZCUyMiUzQTEwNTE0MzIlMkMlMjJfaW5kZXglMjIlM0E4JTdE",
                        "area_name":"高新区",
                        "desc":"禅宗元素经典下午茶",
                        "distance":0,
                        "enjoy_url":"enjoyapp://product/detail?id=1051432",
                        "ext":{
                            "product_type":0,
                            "display_prop":[

                            ],
                            "light_spot":[
                                {
                                    "img":"22796516423653",
                                    "img_url":"https://image.ricebook.com/business/22796516423653",
                                    "title":"以魔方的概念打造三层随意切换的多概念就餐空间",
                                    "type":1,
                                    "content":"成都棕榈泉费尔蒙酒店 Cube 以魔方为概念，在酒店独辟出一处三层楼的空间，打造出多层空间多种概念的餐吧。在 Cube 每一层楼都有自己独立的空间却又相互贯通：位于一层是主打下午茶的大堂吧；位于二层是主打费尔蒙经典鸡尾酒的鸡尾酒吧；三层则是充满现代感的新式居酒屋，目前礼备有2款鸡尾酒，与21款烧酒，及多款威士忌。食客大可在一楼用完下午茶点乘坐电梯直上三楼用餐，用餐结束还可到二楼听着 live show 再小酌一番。"
                                }
                            ]
                        },
                        "origin_price":42400,
                        "price":32800,
                        "product_id":1051432,
                        "product_name":"费尔蒙酒店·CUBE大堂酒廊经典双人下午茶",
                        "sell_state":1,
                        "show_entity_name":"2位"
                    },
                    {
                        "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRmluZm8lMkZwcm9kdWN0X2RldGFpbC5qc29uJTIyJTJDJTIyX3F1ZXJ5JTIyJTNBJTIyc3ViX3Byb2R1Y3RfaWQlM0Q1MDI5NzA0JTI2cHJvZHVjdF9pZCUzRDEwMTU1ODUlMjIlMkMlMjJfZnJvbSUyMiUzQSUyMnJlY29tbWVuZCUyMiUyQyUyMnByb2R1Y3RJZCUyMiUzQTEwMzU5MjIlMkMlMjJfaW5kZXglMjIlM0E5JTdE",
                        "area_name":"盐市口",
                        "desc":"老牌星级酒店品质自助美食",
                        "distance":0,
                        "enjoy_url":"enjoyapp://product/detail?id=1035922",
                        "ext":{
                            "product_type":0,
                            "display_prop":[
                                {
                                    "background_color":"#f6f6f6",
                                    "name":"城中招牌店",
                                    "background_img_color":"red",
                                    "font_color":"#1a1a1a"
                                },
                                {
                                    "background_color":"#f6f6f6",
                                    "name":"地铁沿线",
                                    "background_img_color":"red",
                                    "font_color":"#1a1a1a"
                                }
                            ],
                            "light_spot":[
                                {
                                    "img":"17025366413395",
                                    "img_url":"https://image.ricebook.com/business/17025366413395",
                                    "title":"精致优雅的老牌星级酒店欢享自助美食",
                                    "type":1,
                                    "content":"岷山饭店作为成都老牌的星级酒店，用餐环境与服务水平都让人有宾至如归之感。位于酒店一楼的芝芝咖啡自助餐厅，灯光璀璨却不失端正典雅。光影辉映间，各色美食就像舞台上的演员一般，为客人演绎出丰盛愉快的一餐。靠窗而坐，窗外便是灵动的喷泉花园，花团锦簇尽收眼底。"
                                },
                                {
                                    "img":"20282186423464",
                                    "img_url":"https://image.ricebook.com/business/20282186423464",
                                    "title":"高品质的海鲜档口荟萃鲜活美味",
                                    "type":1,
                                    "content":"芝芝自助餐厅海鲜档口荟萃了丰富而鲜美的海鲜料理，不仅讲究食材的高品质，同时让食客对菜品有更丰富的选择。「芝芝特制香蒜焗扇贝」以浓郁的蒜香配上新鲜的扇贝，鲜活的大海滋味在口中扩散。专业负责的厨师团队精心烹饪，保证高品质食材得意原汁原味纯正释放。"
                                },
                                {
                                    "img":"20282189123528",
                                    "img_url":"https://image.ricebook.com/business/20282189123528",
                                    "title":"环球美食开放式厨房 几十位大厨烹饪丰盛经典美食",
                                    "type":1,
                                    "content":"芝芝咖啡自助餐厅设有多个开放式厨房，几十位大厨有条不紊地忙碌着，通过对新鲜食材的巧妙解读来表现美食的丰富传统与多样。无论是本土地道的「成都风味冒菜」还是异国风情浓郁的「煎德国奶酪香肠」，让食客不出远门就能体验异域风情。芝芝的各式甜点也颇受欢迎，名声在外的「芝芝特式拿破仑」酥脆可口，内馅柔软细腻。"
                                }
                            ]
                        },
                        "origin_price":25070,
                        "price":18800,
                        "product_id":1035922,
                        "product_image_url":"https://image.ricebook.com/business/20282126823439",
                        "product_name":"岷山饭店·芝芝咖啡自助餐厅单人晚市自助",
                        "sell_state":1,
                        "show_entity_name":"位"
                    }
                ]
            },
            "id":12,
            "index":9999
        }
    ],
    "basic":{
        "description":"汤底奶香浓郁 海鲜新鲜到店",
        "display_property_group":[
            {
                "background_color":"#fff0f0",
                "font_color":"#ff3939",
                "name":"超值商品"
            },
            {
                "background_color":"#f6faff",
                "font_color":"#325782",
                "name":"城中招牌店"
            }
        ],
        "is_favorite":false,
        "is_flash":false,
        "left_count":46006,
        "max_count_per_order":500,
        "min_count_per_order":1,
        "name":"朴田泰式海鲜火锅（泛悦国际店）双人餐",
        "offline_time":1505145540000,
        "origin_price":26800,
        "price":22800,
        "product_id":1015585,
        "product_images":[
            {
                "img_url":"https://image.ricebook.com/business/17723378223902",
                "special_show":false
            },
            {
                "img_url":"https://image.ricebook.com/business/17723435523385",
                "special_show":false
            },
            {
                "img_url":"https://image.ricebook.com/business/17723358623901",
                "special_show":true
            },
            {
                "img_url":"https://image.ricebook.com/business/17723362413974",
                "special_show":false
            },
            {
                "img_url":"https://image.ricebook.com/business/17723360123421",
                "special_show":false
            },
            {
                "img_url":"https://image.ricebook.com/business/17723375723382",
                "special_show":false
            },
            {
                "img_url":"https://image.ricebook.com/business/17723357323900",
                "special_show":false
            },
            {
                "img_url":"https://image.ricebook.com/business/18137675013766",
                "special_show":false
            },
            {
                "img_url":"https://image.ricebook.com/business/18137675013058",
                "special_show":false
            },
            {
                "img_url":"https://image.ricebook.com/business/18137675013380",
                "special_show":false
            }
        ],
        "product_type":0,
        "refund_type":2,
        "sell_begin_time":1470240000000,
        "sell_end_time":1505145540000,
        "sell_state":5,
        "server_time":1520944815610,
        "share_info":{
            "sub_title":"分享赢礼券",
            "text":"好友从你分享的链接注册 ENJOY 并消费，你可获得价值 50 元礼券，多邀多得。"
        },
        "shelving_time":1470240000000,
        "short_name":"朴田泰式海鲜火锅（泛悦国际店）双人餐",
        "show_entity_name":"2位",
        "spec":"特配双人餐",
        "sub_product_array":[
            {
                "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRmluZm8lMkZwcm9kdWN0X2RldGFpbC5qc29uJTIyJTJDJTIyX3F1ZXJ5JTIyJTNBJTIyc3ViX3Byb2R1Y3RfaWQlM0Q1MDI5NzA0JTI2cHJvZHVjdF9pZCUzRDEwMTU1ODUlMjIlMkMlMjJfaW5kZXglMjIlM0EwJTJDJTIyc3ViUHJvZHVjdElkJTIyJTNBNTAyOTcwNCU3RA==",
                "is_flash":false,
                "is_promotion":false,
                "name":"朴田泰式海鲜火锅（泛悦国际店）双人餐",
                "origin_price":26800,
                "pass_info":[

                ],
                "price":22800,
                "sell_state":5,
                "show_entity_name":"2位",
                "spec":"特配双人餐",
                "sub_product_id":5029704
            },
            {
                "trace_meta":"JTdCJTIyX3VyaSUyMiUzQSUyMiUyRmluZm8lMkZwcm9kdWN0X2RldGFpbC5qc29uJTIyJTJDJTIyX3F1ZXJ5JTIyJTNBJTIyc3ViX3Byb2R1Y3RfaWQlM0Q1MDI5NzA0JTI2cHJvZHVjdF9pZCUzRDEwMTU1ODUlMjIlMkMlMjJfaW5kZXglMjIlM0ExJTJDJTIyc3ViUHJvZHVjdElkJTIyJTNBNTAyOTcwNSU3RA==",
                "is_flash":false,
                "is_promotion":false,
                "name":"朴田泰式海鲜火锅（泛悦国际店）双人餐",
                "origin_price":38800,
                "pass_info":[

                ],
                "price":32800,
                "sell_state":5,
                "show_entity_name":"2位",
                "spec":"尊享双人餐",
                "sub_product_id":5029705
            }
        ],
        "sub_product_id":5029704
    }
}
                  axios.post('/api/savedetail',pro)
                        .then(function(res){
                            console.log(res)
                        })
            }





		}
	}


</script>
<style></style>



